Azure/azure-sdk-for-node

lib/services/computeManagement/README.md
Looks like `virtualMachineImages` no longer exists and has been broken up into multiple objects.
`virtualMachineVMImages` gave me the info I needed to list all images, not sure if `virtualMachineOSImages` was needed instead though.
=> Fix name of virtual machine images

lib/services/computeManagement/README.md
Without the encoding specified, the pem file is read in as a buffer instead of a string.
This would then fail the argument validation requirement for credentials.pem since it wanted a string and got a buffer.
Without the encoding I was unable to run this example.
With the encoding specified, I am able to run the example.
=> Specify pem file encoding

package.json
It appears people have different versions of jshint which all match our old range, but some errors are only reported from a specific version, this causes confusion.
=> fix jshint version

lib/services/extra/package.json
This is a temporary package owned by us, so use it to test new ci job to publish to npm
=> pump up the version so to test publish through jenkins ci

README.md, package.json
As a developer I expect to be able to clone the repo, do an `npm install` and then run `npm test` to see all tests passing. This is not currently the case. The travis CI script pulls down the CLI and the node project, then does some npm linking, which leads to different results than just pulling down the project and running the tests. This will allow the tests to pass when the project is cloned, installed and tested.
Post this PR, there should be though given to how travis executes. There certainly is value in testing the CLI project with the SDK, but we may want to build the links after the SDK has run through it's own test suite.
=> npm test fails after cloning and running npm install

lib/common/package.json
Update validator module to version 3.22.2 (same version as in azure-storage module) to fix security vulnerability (https://github.com/Azure/azure-sdk-for-node/issues/1425).
All unit tests seems good.
=> Update validator module to fix security issue

package.json, scripts/each-service.js, scripts/setup.js, scripts/teardown.js
Iterate over the services directory and read out the package names instead of maintaining that giant array.
Also adds a teardown script to remove the global changes done by setup.js.
=> Updated setup.js script to automatically find services

lib/services/commerce/package.json
Received the following during the build:
npm ERR! "You cannot publish over the previously published version 0.1.0." : azure-arm-commerce
npm ERR! 
this change will fix it
=> Rev'd the version of the commerce package

lib/services/monitoring/lib/eventsClient.js, package.json
Update events client to use api version 2014-04-01. Events stopped supported YYYY-MM version recently, and this is breaking group log CLI commands
=> Update events client to use api version 2014-04-01

lib/services/webSiteManagement/README.md, lib/services/webSiteManagement2/README.md
When you copy and paste the code sample from the README.md file, it doesn't work without this fix.
`createWebsiteManagementClient` -> `createWebSiteManagementClient`
=> Fix a typo in website management README.md

lib/services/legacyStorage/lib/blob/blobservice.js
The Node API is currently missing the method to get the status of Blob copying. This is troublesome especially when copying large blobs like VHD images (e.g. when transferring VMs from one subscription to another).
This commit fixes that. Programmed according to this reference: http://blog.elastacloud.com/2012/07/04/copying-azure-blobs-from-one-subscription-to-another-with-api-1-7-1/ and checked working.
There is also a test prepared for the method in the with-test branch, but I don't have the knowledge to emulate the Nock mockup at this time, so the test is failing.
=> Added BlobService.statusOfCopyBlob, method to get the status of a blob copy operation

lib/services/extra/lib/graphRbacManagementClient.js, lib/services/extra/package.json
This also searches for object ids in the partner tenant (artemis/CSP scenario)
=> Graph: Add the includeDirectoryObjectReferences flag to the GetObjectsByObjectIds call 

package.json
Per modern "package.json" best practices (see also: https://docs.npmjs.com/files/package.json)
Issue: https://github.com/Azure/azure-sdk-for-node/issues/1512
=> Using "license" in package.json instead of "licenses" array

lib/services/keyVault/README.md
There was a broken link (pointing directly to a Git branch `dev` that does not exist)
=> Updating README.md for Azure KeyVault service

lib/common/package.json
I made a change to Azure Common (to service.js) to enable passing in
options to service client construction. This is required for the new
packages that have been added for DataLake*
=> Update the version of azure-common

lib/services/dnsManagement/package.json
When using the dnsManagement package in isolation, the package can fail because `underscore` is not defined in the package.json. I've added it in to the package.json so `npm install` will correctly place the modules
=> fixed missing dep for underscore in dnsManagement package

lib/common/lib/util/keyFiles.js
Depending on the version of openssl used to generate the management certificates
the private key may take one of two forms:
PKCS1 (Old, Currently Supported by us):
-----BEGIN RSA PRIVATE KEY-----
BASE64 ENCODED DATA
-----END RSA PRIVATE KEY-----
PKCS8 (New, Support added in this commit):
-----BEGIN PRIVATE KEY-----
BASE64 ENCODED DATA
-----END PRIVATE KEY-----
This commit adds support for the PKCS8 format. Prior to this commit using the PKCS8
format as part of a .pem would result in authentication failure as the key
would be undefined.
=> Add support for x509 pem files using `BEGIN/END PRIVATE KEY`

test/services/keyVault/keyVault-key-tests.js
Add AZURE_KV_STANDARD_VAULT_ONLY env variable to optionally disable premium operations in KeyVault tests.
=> KeyVault: Allow testing of standardvaultonly regions

lib/services/dataLake.Analytics/README.md, lib/services/dataLake.Analytics/package.json, lib/services/dataLake.Store/README.md, lib/services/dataLake.Store/package.json
remove key vault as related
Change naming to adhere to our official naming
Rev versions.
=> One more round of doc changes for DataLake

lib/azure.js
Hi,
This commit adds missing export for TableUtilities module
from azure-storage.
The existing documentation and source code from samples
do expect this module on azure instance without direct import or `azure-storage`:
```JavaScript
var entityGen = azure.TableUtilities.entityGenerator
```
Thanks!
=> :bug: Add missing TableUtilities export. Fixes #1507

CONTRIBUTING.md
This PR fixes a link to Azure projects contributing guidelines (yes)
Thanks!
=> :bug: Fix link to guidelines in Contributing.md

lib/azure.js
This commit adds missing export for TableBatch module
to global azure module.
Without that export that is not possible to write:
var batch = new azure.TableBatch()
as envisioned in documentation on using azure module
Thanks!
=> :bug: Add TableBatch export to azure. Fixes #1590

lib/services/scheduler/lib/scheduler.js
cloudServiceName should be the first parameter and credentials should be the third.
=> Fixed parameter ordering for createSchedulerClient

examples/samples/retrypolicysample.js
This commit updates implementation of retrypolicysample.
- updated Azure SDK module version
- updated Azure SDK implementation syntax
- cleaner names for callback arguments
- whit space fixes
When run example will output:
Created the container retrypolicysample
Deleted the container retrypolicysample
Made the request at Wed, 27 Jan 2016 22:25:58 GMT, received StatusCode: 409
Thanks!
=> :art: Update retrypolicysample

lib/services/keyVaultManagement/lib/keyVaultManagementClient.js, lib/services/keyVaultManagement/package.json
I missed 2 places with the retired API version in the previous commit, adding them now.
=> Updating Key Vault management API version in 2 more places

gulpfile.js, lib/services/dataLake.Analytics/lib/catalog/models/index.d.ts, lib/services/dataLake.Analytics/lib/catalog/models/uSqlTablePartition.js, lib/services/dataLake.Analytics/lib/job/operations/job.js, lib/services/dataLake.Analytics/package.json
This is an update based on the latest swagger:
Switch GetStatistics from POST to GET
Add two new properties to USqlTablePartition: ParentName and CreateDate.
=> ADLA Swagger update

lib/common/package.json
Regular Expression Denial of Service
azure-common@0.9.16 > request@2.45.0 > hawk@1.1.1
=> Update the dependency package 'request' to version 2.69.0 to address the security vulunerablities found by NSP check

lib/common/lib/services/serviceclient.js
When `options` is null, then the setting for `DEFAULT_CLIENT_REQUEST_TIMEOUT` is not correctly applied (so requests will _never_ timeout).
If `options` is null, set it to an empty object.
=> fixed bug where null options object prevents defaults from being set

swagger_to_sdk_config.json
This is required to ensure that we properly regenerate the Node code for ADL
=> update to latest job swagger for ADLA

lib/services/HDInsight2/lib/hDInsightManagementClient.js
When creating a new hd insight cluster, enabling to configure a storage profile and inside storage accounts associated with it.
This pull request resolves #1849
=> add storage profile with new hd insight cluster

swagger_to_sdk_config.json
Doing this ahead of submission of these new swagger specs so that they
get picked up by the auto-gen tool.
=> Update API versions to the next version

lib/services/sqlManagement/lib/sqlManagementClient.js
This would add correct attributes for BlobCredentials element in sql export method request body.
SQL export documentation is available below.
https://msdn.microsoft.com/en-us/library/azure/dn781282.aspx
=> #2009 - fix for SQL export method

Extensions/azure-node-essentials/README.md, Extensions/azure-node-essentials/changelog.md, Extensions/azure-node-essentials/extension.js, Extensions/azure-node-essentials/package.json
1. Fixing an annoying bug in mac, where we would always update the package on every instance of VSCode activation.
2. updated readme with more scenarios
=> Package check for mac and other fixes

runtime/ms-rest/lib/constants.js, runtime/ms-rest/lib/filters/userAgentFilter.js, runtime/ms-rest/lib/msRest.js, runtime/ms-rest/lib/serviceClient.js
These are the runtime changes required to send userAgent string in request headers. See issue #2076
This adds a `addUserAgentInfo` to the service client which is the base class for any concrete azure service client. So, autorest generated service clients or any 3rd party libraries can simply call this method and pass in their package name and module version in the format `module_name/package_version`.
The runtime then constructs the user agent string via an user agent filter as part of the request pipeline and sends it along.
This is part 1 of the runtime changes. See #2078 for why runtime changes need to be made independently.
=> msrest - send user agent info in request headers

runtime/ms-rest/lib/serviceClient.js
This is part of work for https://github.com/Azure/azure-sdk-for-node/issues/2076
Motivation:
To send user agent information from azure packages, we have to read its package.json. It turns out that package.json isn't always in the same relative path from the service client itself. So, this helper on the base service client helps to locate package.json and send back the required info. This will be consumed by azure clients generated from autorest.
=> get info from package json

runtime/ms-rest/package.json
after my previous change to expose a way to read package.json for
telemetry data.
This is part of work for #2076
patch version needs to be bumped up due to this change: #2084
=> update patch version for msrest

runtime/ms-rest-azure/package.json
after my previous change to expose a way to read package.json for
telemetry data.
This is part of work for #2076
patch version needs to be bumped up due to this change: #2084
=> update patch version for msrestazure

runtime/ms-rest/lib/filters/userAgentFilter.js, runtime/ms-rest/lib/serviceClient.js, runtime/ms-rest/package.json
1. ensure that this filter is executed last and other user-agent
filters, if any (xplat-cli has its own) are executed first. That way,
the right user agent header is set. So we call the other filters in the
chain first and apply our function when the callstack unwinds. By now,
if another filter had set the user agent header, we wont bother setting
it.
2. check if a particular bit of useragent info is already present before
inserting it. safe fix for #2091
=> Fixes for user agent header

lib/services/keyVault/lib/keyvault.d.ts, lib/services/keyVault/package.json
- Make options optional in KeyVaultClient constructor
- Use better type in CreateKey method
- bump up patch version in package.json
Follow up to #2136 and getting ready to publish a patch.
Fixes https://github.com/Azure/azure-sdk-for-node/issues/2124
=> Minor fixes to keyvault.d.ts

runtime/ms-rest-azure/Changelog.md, runtime/ms-rest-azure/package.json, runtime/ms-rest/Changelog.md, runtime/ms-rest/lib/serialization.js, runtime/ms-rest/lib/webResource.js, runtime/ms-rest/package.json
- fixes this https://github.com/Azure/oav/issues/111
- removed native code `Buffer.isBuffer()` and replaced it with a browser compatible package.
=> changes to ms-rest

lib/services/dataLake.Store/lib/datalakeStore.d.ts
This fixes typescript compile issue due to naming mismatch between d.ts and associated js files.
Changed the property names in the dataLakeStore.d.ts file to match the associated dataLakeStore.js file
=> corrected import stmt names in ts file to match dataLakeStore.js

lib/services/intune/README.md
Added a note that the module is deprecated and added a link to the graph
API docs.
Related to #2241
=> Added deprecation notice to intune module.

lib/services/serviceBus/lib/servicebusservice.js
This function creates a queue, but the documentation for the `queuePath` param implies delete. Corrected.
=> doc fix, param incorrectly implied delete occurs

runtime/ms-rest-azure/Changelog.md, runtime/ms-rest-azure/index.d.ts, runtime/ms-rest-azure/lib/azureServiceClient.js, runtime/ms-rest-azure/lib/constants.js, runtime/ms-rest-azure/lib/login.js, runtime/ms-rest-azure/lib/msRestAzure.js, runtime/ms-rest-azure/package.json, runtime/ms-rest-azure/test/credTests.js, runtime/ms-rest-azure/test/data/auth-customEnv.json, runtime/ms-rest-azure/test/data/auth-usProd.json, runtime/ms-rest-azure/test/rpRegistrationFilterTests.js, runtime/ms-rest-azure/test/testlist.txt, runtime/ms-rest/Changelog.md, runtime/ms-rest/lib/msRest.js, runtime/ms-rest/lib/utils.js, runtime/ms-rest/package.json
- @balajikris @yugangw-msft - Please review
=> support for authentication using sp from auth file

.gitignore, package-lock.json, package.json, scripts/unit-arm.js, scripts/unit-coverage.js
mochaJs have [removed](https://github.com/mochajs/mocha/issues/2356) their coverage implementation. This is why after running `npm run coverage` we get the following error `Error: invalid reporter "html-cov"`.
I'm adding [istanbulJs](https://istanbul.js.org/) in order to fix the coverage in this project.
You can test this PR by running `npm run coverage`, you should see the following result:
A detailed html report will be created in `/coverage/index.html`
=> removing mocha html-cov and replacing it with istanbulJS

README.md
The README file table was misaligned, likely due to a copy paste error.
=> Fixed a typo in the Readme

runtime/ms-rest/index.d.ts
Adding properties to the typings in a couple of types to expose essential properties. For example, every one of the credentials classes in this repos assigned directly to webResource.headers, and without response.statusCode HttpOperationResponse is basically useless.
=> Updated typings to include needed properties that already exist

runtime/ms-rest-azure/lib/cloudError.js
ARM error schema conforms to the [OData 4.0](http://docs.oasis-open.org/odata/odata-json-format/v4.0/os/odata-json-format-v4.0-os.html#_Toc372793091) spec, which declares the innerError field as an extension point.
I'm working on Azure Policy, and there is an upcoming change to ARM after which any PUT/PATCH request to any resource provider may return an error containing the innerError field in case the request is violating one of the policies. Because it's a part of ARM contract and is not specific to an RP, CloudError contract should be the right place for this change.
=> Add innerError field to CloudError contract

package-lock.json, package.json, scripts/runtime-install.js
-`npm run runtime-install`: will remove the `ms-rest` and ms-rest-azure` node_modules and connect the local versions of each.
-script will also be run as part of `npm test`
=> Added script for installing local runtime

runtime/ms-rest/Changelog.md, runtime/ms-rest/lib/serialization.js, runtime/ms-rest/package.json, runtime/ms-rest/test/data/TestClient/lib/models/fish.js, runtime/ms-rest/test/data/TestClient/lib/models/sawshark.js, runtime/ms-rest/test/data/TestClient/lib/models/shark.js, runtime/ms-rest/test/serializationTests.js
- follow up from https://github.com/Azure/azure-sdk-for-node/pull/2332, deals with missing polymorphic 
discriminator in response
- during runtime, discriminator property is populated with the expected value if missing.
=> Serialization changes, remove requirement for polymorphic discriminator type in json

lib/services/serviceBus/package.json
This moves to the latest version of the mpns module, version 2.1.3.
The module has no changes other than incrementing the version and
updating the package.json to include the "license" property. This is
to help make it clear that the mpns module has the MIT license at
this time, making automated security and copyright analysis easy!
I am the author of the 'mpns' module, FYI.
=> azure-sb: updated 'mpns' module

lib/azure.js
AzureEnvironment name fixed
- msRestAzure.AzureEnvironment.Aure -> msRestAzure.AzureEnvironment.Azure
=> fix typo while declaring AzurePublicCloudEnvironment

runtime/ms-rest-azure/Changelog.md, runtime/ms-rest-azure/index.d.ts, runtime/ms-rest-azure/lib/credentials/keyVaultCredentials.js, runtime/ms-rest-azure/lib/msRestAzure.js, runtime/ms-rest-azure/package-lock.json, runtime/ms-rest-azure/package.json
Part 1 of: https://github.com/Azure/azure-sdk-for-node/issues/2393
-support for directly consuming other auth credentials.
=> Adding runtime dependency for new keyvault data-plane changes

gulpfile.js
After adding Swagger to SDK config to azure-rest-api-specs, we start getting new config settings like `output-folder: $(node-sdks-folder)/lib/services/keyVaultManagement/lib`. This breaks local regeneration with `gulp codegen` because there's no `node-sdks-folder` variable defined.
The solution for this could be to read the swagger_to_sdk_config.json and apply the autorest settings in `gulp codegen`. The path of least resistance, though, is just to specify `nodejs.output-folder` instead of `output-folder` in `gulpfile.js` so that our local output-folder setting binds tighter than the one retrieved from azure-rest-api-specs. This seems less likely to break projects in gulp codegen, so that's what I'm doing for now.
=> Use nodejs.output-folder autorest argument

lib/services/cdnManagement/lib/cdnManagementClient.d.ts, lib/services/cdnManagement/lib/cdnManagementClient.js
Created to accumulate context: cdn/resource-manager
- Added `CheckNameAvailabilityWithSubscription()`
=> [AutoPR] cdn/resource-manager

lib/services/cosmosdbManagement/lib/cosmosDBManagementClient.d.ts, lib/services/cosmosdbManagement/lib/cosmosDBManagementClient.js, lib/services/cosmosdbManagement/lib/models/capability.js, lib/services/cosmosdbManagement/lib/models/index.d.ts
Created to accumulate context: cosmos-db/resource-manager
=> [AutoPR] cosmos-db/resource-manager

codegen_mappings.json, codegen_mappings.schema.json, gulpfile.js
Adding a JSON schema for codegen_mappings.json doesn't add any functionality, but it does add editor IntelliSense and descriptions. The descriptions are always a good reminder for what a property is used for.
If we add more properties to each of the package objects within codegen_mappings.json, a schema is a great way to ensure that you didn't forget to add required properties to any packages.
=> Add codegen_mappings schema file and small gulpfile tweak

lib/services/serviceBusManagement2/lib/models/correlationFilter.js, lib/services/serviceBusManagement2/lib/models/index.d.ts, lib/services/serviceBusManagement2/lib/models/rule.js, lib/services/serviceBusManagement2/lib/models/sBQueue.js, lib/services/serviceBusManagement2/lib/operations/index.d.ts, lib/services/serviceBusManagement2/lib/operations/queues.js, lib/services/serviceBusManagement2/lib/operations/rules.js, lib/services/serviceBusManagement2/lib/serviceBusManagementClient.d.ts, lib/services/serviceBusManagement2/lib/serviceBusManagementClient.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2730
=> [AutoPR servicebus/resource-manager] ServiceBus: added 'properties' to CorrelationFilter

lib/services/monitorManagement/lib/models/actionGroupResource.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2841
=> [AutoPR monitor/resource-manager] fix documentation bug: max length of Group Short Name should be 12

lib/services/apimanagement/lib/models/additionalLocation.js, lib/services/apimanagement/lib/models/apiManagementServiceBaseProperties.js, lib/services/apimanagement/lib/models/apiManagementServiceResource.js, lib/services/apimanagement/lib/models/apiManagementServiceUpdateParameters.js, lib/services/apimanagement/lib/models/index.d.ts
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2881
=> [AutoPR apimanagement/resource-manager] add readonly property private ip address in addtional location

lib/services/contentModerator/lib/operations/index.d.ts, lib/services/contentModerator/lib/operations/textModeration.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2884
=> [AutoPR cognitiveservices/data-plane/ContentModerator] Set language parameter as a non-required field for Screen Text API

lib/services/apimanagement/lib/operations/apiIssue.js, lib/services/apimanagement/lib/operations/apiIssueAttachment.js, lib/services/apimanagement/lib/operations/apiIssueComment.js, lib/services/apimanagement/lib/operations/index.d.ts
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2893
=> [AutoPR apimanagement/resource-manager] ApiIssue HEAD operation name consistent across the spec

lib/services/serviceBusManagement2/lib/operations/index.d.ts, lib/services/serviceBusManagement2/lib/operations/queues.js, lib/services/serviceBusManagement2/lib/operations/rules.js, lib/services/serviceBusManagement2/lib/operations/subscriptions.js, lib/services/serviceBusManagement2/lib/operations/topics.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2952
=> [AutoPR servicebus/resource-manager] Service Bus: added $skip and $top to list calls

lib/services/automationManagement/lib/models/hybridRunbookWorker.js, lib/services/automationManagement/lib/models/index.d.ts, lib/services/automationManagement/lib/models/jobCollectionItem.js, lib/services/automationManagement/lib/models/linuxProperties.js, lib/services/automationManagement/lib/models/softwareUpdateConfiguration.js, lib/services/automationManagement/lib/models/updateConfiguration.js, lib/services/automationManagement/lib/models/webhook.js, lib/services/automationManagement/lib/models/windowsProperties.js, lib/services/automationManagement/lib/operations/hybridRunbookWorkerGroupOperations.js, lib/services/automationManagement/lib/operations/index.d.ts, lib/services/automationManagement/lib/operations/jobScheduleOperations.js, lib/services/automationManagement/lib/operations/softwareUpdateConfigurations.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2943
=> [AutoPR automation/resource-manager] Added x-mx-odata properties for some resources

lib/services/computeManagement2/lib/models/dataDisk.js, lib/services/computeManagement2/lib/models/index.d.ts, lib/services/computeManagement2/lib/models/oSDisk.js, lib/services/computeManagement2/lib/models/storageProfile.js, lib/services/computeManagement2/lib/models/virtualMachine.js, lib/services/computeManagement2/lib/models/virtualMachineScaleSet.js, lib/services/computeManagement2/lib/models/virtualMachineScaleSetOSDisk.js, lib/services/computeManagement2/lib/models/virtualMachineScaleSetStorageProfile.js, lib/services/computeManagement2/lib/models/virtualMachineScaleSetVM.js, lib/services/computeManagement2/lib/models/virtualMachineScaleSetVMProfile.js, lib/services/computeManagement2/lib/models/virtualMachineUpdate.js, lib/services/computeManagement2/lib/operations/index.d.ts, lib/services/computeManagement2/lib/operations/virtualMachineScaleSetVMs.js, lib/services/computeManagement2/lib/operations/virtualMachineScaleSets.js, lib/services/computeManagement2/lib/operations/virtualMachines.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2977
=> [AutoPR compute/resource-manager] fixed formatting

lib/services/monitorManagement/lib/models/actionGroupResource.js, lib/services/monitorManagement/lib/models/alertingAction.js, lib/services/monitorManagement/lib/models/azNsActionGroup.js, lib/services/monitorManagement/lib/models/index.d.ts, lib/services/monitorManagement/lib/models/logSearchRuleResource.js, lib/services/monitorManagement/lib/models/source.js, lib/services/monitorManagement/lib/operations/index.d.ts, lib/services/monitorManagement/lib/operations/scheduledQueryRules.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2998
=> [AutoPR monitor/resource-manager] Minor Updates - description text

lib/services/batchaiManagement/lib/models/index.d.ts, lib/services/batchaiManagement/lib/models/jobCreateParameters.js, lib/services/batchaiManagement/lib/operations/experiments.js, lib/services/batchaiManagement/lib/operations/index.d.ts, lib/services/batchaiManagement/lib/operations/jobs.js, lib/services/batchaiManagement/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3038
=> [AutoPR batchai/resource-manager] BatchAI. Several fixes

lib/services/monitorManagement/lib/models/alertingAction.js, lib/services/monitorManagement/lib/models/azNsActionGroup.js, lib/services/monitorManagement/lib/models/index.d.ts, lib/services/monitorManagement/lib/models/logSearchRuleResource.js, lib/services/monitorManagement/lib/models/metricAlertResource.js, lib/services/monitorManagement/lib/models/metricAlertResourcePatch.js, lib/services/monitorManagement/lib/models/source.js, lib/services/monitorManagement/lib/operations/index.d.ts, lib/services/monitorManagement/lib/operations/metricAlerts.js, lib/services/monitorManagement/lib/operations/scheduledQueryRules.js, lib/services/monitorManagement/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3108
=> [AutoPR monitor/resource-manager] Add "autoMitigate" to Metric Alert API spec for 2018-03-01

lib/services/containerservicesManagement/lib/operations/index.d.ts, lib/services/containerservicesManagement/lib/operations/managedClusters.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3098
=> [AutoPR containerservices/resource-manager] [AKS] add POST endpoint for fetching accessProfiles

lib/services/applicationinsights/lib/operations/index.d.ts, lib/services/applicationinsights/lib/operations/webTests.js, lib/services/applicationinsights/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3126
=> [AutoPR applicationinsights/resource-manager] [AppInsights] Added webtests-by-component API to 2015-05-01

lib/services/servermanagement/LICENSE.txt, lib/services/servermanagement/README.md, lib/services/servermanagement/lib/serverManagement.d.ts, lib/services/servermanagement/lib/serverManagement.js, lib/services/servermanagement/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3140
=> [AutoPR servermanagement/resource-manager] Fix Python conf of servermanager

lib/services/keyvault/lib/keyVaultClient.d.ts, lib/services/keyvault/lib/keyVaultClient.js, lib/services/keyvault/lib/models/certificateBundle.js, lib/services/keyvault/lib/models/certificateCreateParameters.js, lib/services/keyvault/lib/models/certificateImportParameters.js, lib/services/keyvault/lib/models/certificatePolicy.js, lib/services/keyvault/lib/models/certificateUpdateParameters.js, lib/services/keyvault/lib/models/index.d.ts, lib/services/keyvault/lib/models/keyCreateParameters.js, lib/services/keyvault/lib/models/keyProperties.js, lib/services/keyvault/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3136
=> [AutoPR keyvault/data-plane] RSA key size examples, ECC descriptions

lib/services/automationManagement/lib/models/hybridRunbookWorkerGroup.js, lib/services/automationManagement/lib/models/index.d.ts
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3132
=> [AutoPR automation/resource-manager] Added GroupType property in HybridWorkerGroup

lib/services/eventgrid/lib/models/deviceLifeCycleEventProperties.js, lib/services/eventgrid/lib/models/index.d.ts
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3174
=> [AutoPR eventgrid/data-plane] Replacing # with &#35;

lib/services/containerservicesManagement/lib/models/index.d.ts, lib/services/containerservicesManagement/lib/models/managedClusterAgentPoolProfile.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3178
=> [AutoPR containerservices/resource-manager] [AKS] remove maxPods default

lib/services/iotcentral/lib/iotCentralClient.d.ts, lib/services/iotcentral/lib/iotCentralClient.js, lib/services/iotcentral/lib/operations/apps.js, lib/services/iotcentral/lib/operations/operations.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3185
=> [AutoPR iotcentral/resource-manager] Remove subscriptionId uuid format for IotCentral

lib/services/keyvault/lib/lib/keyVaultClient.d.ts, lib/services/keyvault/lib/lib/keyVaultClient.js, lib/services/keyvault/lib/lib/models/certificateBundle.js, lib/services/keyvault/lib/lib/models/certificateCreateParameters.js, lib/services/keyvault/lib/lib/models/certificateImportParameters.js, lib/services/keyvault/lib/lib/models/certificatePolicy.js, lib/services/keyvault/lib/lib/models/certificateUpdateParameters.js, lib/services/keyvault/lib/lib/models/index.d.ts, lib/services/keyvault/lib/lib/models/jsonWebKey.js, lib/services/keyvault/lib/lib/models/keyBundle.js, lib/services/keyvault/lib/lib/models/keyImportParameters.js, lib/services/keyvault/lib/lib/models/keyProperties.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3199
=> [AutoPR keyvault/data-plane] [KeyVault] Adding descriptions to JsonWebKey kty values

lib/services/keyvault/lib/lib/keyVaultClient.d.ts, lib/services/keyvault/lib/lib/keyVaultClient.js, lib/services/keyvault/lib/lib/models/certificateBundle.js, lib/services/keyvault/lib/lib/models/certificateCreateParameters.js, lib/services/keyvault/lib/lib/models/certificateImportParameters.js, lib/services/keyvault/lib/lib/models/certificatePolicy.js, lib/services/keyvault/lib/lib/models/certificateUpdateParameters.js, lib/services/keyvault/lib/lib/models/index.d.ts, lib/services/keyvault/lib/lib/models/keyProperties.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3198
=> [AutoPR keyvault/data-plane] [KeyVault] Adding crv to KeyProperties for EC certificate support

runtime/ms-rest-azure/Changelog.md, runtime/ms-rest-azure/index.d.ts, runtime/ms-rest-azure/package.json
Fixes #2952
`validateAuthority` was missing from the type definitions. Because we want to make it easy for users to see what values are used in a given AzureEnvironment, we're using the string and boolean literal types and building something that needs to be assignable to AzureEnvironment.
=> Validate authority

lib/services/computerVision/lib/computerVisionAPIClient.d.ts, lib/services/computerVision/lib/computerVisionAPIClient.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3222
=> [AutoPR cognitiveservices/data-plane/ComputerVision] Add Spanish as an option as ServiceLanguage for ComputerVision

lib/services/networkManagement2/lib/models/index.d.ts, lib/services/networkManagement2/lib/models/probe.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3230
=> [AutoPR network/resource-manager] network: add https probe which was missing in the spec

lib/services/sqlManagement2/lib/models/index.d.ts, lib/services/sqlManagement2/lib/models/index.js, lib/services/sqlManagement2/lib/models/serverSecurityAlertPolicy.js, lib/services/sqlManagement2/lib/operations/index.d.ts, lib/services/sqlManagement2/lib/operations/index.js, lib/services/sqlManagement2/lib/operations/serverSecurityAlertPolicies.js, lib/services/sqlManagement2/lib/sqlManagementClient.d.ts, lib/services/sqlManagement2/lib/sqlManagementClient.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3240
=> [AutoPR sql/resource-manager] adding new state value to keep backward competiblity

package-lock.json, package.json, runtime/ms-rest-azure/package-lock.json
Published https://npmjs.com/package/azure-loganalytics, now consuming it from rollup package so we can `require('azure').createLogAnalyticsClient()` @alexeldeib
=> Add loganalytics to rollup package

lib/services/apimanagement/lib/models/errorResponse.js, lib/services/apimanagement/lib/models/index.d.ts, lib/services/apimanagement/lib/operations/index.d.ts, lib/services/apimanagement/lib/operations/productApi.js, lib/services/apimanagement/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3258
=> [AutoPR apimanagement/resource-manager] Fix the validation Check for apiId parameter in the productapis

lib/services/face/README.md
In `README.md` of `azure-sdk-for-node/lib/services/face/`, `new FaceAPIClient` should have parameter `azureRegion`, and `returnFaceAttributes` should be an array, not a comma-delimited list
=> Documentation fixes

lib/services/monitorManagement/lib/models/action.js, lib/services/monitorManagement/lib/models/alertingAction.js, lib/services/monitorManagement/lib/models/diagnosticSettingsResource.js, lib/services/monitorManagement/lib/models/eventData.js, lib/services/monitorManagement/lib/models/index.d.ts, lib/services/monitorManagement/lib/models/logMetricTrigger.js, lib/services/monitorManagement/lib/models/metricAlertAction.js, lib/services/monitorManagement/lib/models/metricAlertStatus.js, lib/services/monitorManagement/lib/models/metricAlertStatusProperties.js, lib/services/monitorManagement/lib/models/metricCriteria.js, lib/services/monitorManagement/lib/models/metricDimension.js, lib/services/monitorManagement/lib/models/triggerCondition.js, lib/services/monitorManagement/lib/operations/alertRules.js, lib/services/monitorManagement/lib/operations/autoscaleSettings.js, lib/services/monitorManagement/lib/operations/diagnosticSettingsOperations.js, lib/services/monitorManagement/lib/operations/index.d.ts
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3285
=> [AutoPR monitor/resource-manager] Add two missing "by subscription" operations for completeness and compliance

lib/services/serviceBusManagement2/lib/models/armDisasterRecovery.js, lib/services/serviceBusManagement2/lib/models/index.d.ts, lib/services/serviceBusManagement2/lib/models/migrationConfigProperties.js, lib/services/serviceBusManagement2/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3314
=> [AutoPR servicebus/resource-manager] ServiceBus: Added property pendingReplicationOperationsCount to GeoDR and Migration

lib/services/eventHubManagement/lib/models/armDisasterRecovery.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3329
=> [AutoPR eventhub/resource-manager] EventHub: Removed space from pendingReplicationOperationsCount

lib/services/networkManagement2/lib/operations/index.d.ts, lib/services/networkManagement2/lib/operations/vpnConnections.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3344
=> [AutoPR network/resource-manager] Fixed typos. Fixes issue 1770 in .NET SDK

lib/services/computeManagement2/lib/models/index.d.ts, lib/services/computeManagement2/lib/models/runCommandResult.js, lib/services/computeManagement2/lib/operations/index.d.ts, lib/services/computeManagement2/lib/operations/virtualMachineScaleSetVMs.js, lib/services/computeManagement2/lib/operations/virtualMachines.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3364
=> [AutoPR compute/resource-manager] Update RunCommand operation output as valid json object

lib/services/automationManagement/lib/operations/index.d.ts, lib/services/automationManagement/lib/operations/runbookDraftOperations.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3420
=> [AutoPR automation/resource-manager] Changing schema from string to file

lib/services/monitorManagement/lib/models/autoscaleProfile.js, lib/services/monitorManagement/lib/models/index.d.ts, lib/services/monitorManagement/lib/models/recurrence.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3468
=> [AutoPR monitor/resource-manager] updated description of recurrent frequency

lib/services/datafactoryManagement/lib/models/activity.js, lib/services/datafactoryManagement/lib/models/forEachActivity.js, lib/services/datafactoryManagement/lib/models/ifConditionActivity.js, lib/services/datafactoryManagement/lib/models/index.d.ts, lib/services/datafactoryManagement/lib/models/pipelineResource.js, lib/services/datafactoryManagement/lib/models/untilActivity.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3493
=> [AutoPR datafactory/resource-manager] [Datafactory] Bringing back additionalProperties in Activity removed by mistake

lib/services/computerVision/lib/computerVisionClient.d.ts, lib/services/computerVision/lib/computerVisionClient.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3486
=> [AutoPR cognitiveservices/data-plane/ComputerVision] ComputerVision: bug fixes for /describe and /analyze [breaking]

lib/services/websiteManagement2/lib/operations/appServiceEnvironments.js, lib/services/websiteManagement2/lib/operations/appServicePlans.js, lib/services/websiteManagement2/lib/operations/index.d.ts, lib/services/websiteManagement2/lib/operations/recommendations.js, lib/services/websiteManagement2/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3550
=> [AutoPR web/resource-manager] Fix documentation issues with metrics APIs

lib/services/datafactoryManagement/lib/dataFactoryManagementClient.d.ts, lib/services/datafactoryManagement/lib/dataFactoryManagementClient.js, lib/services/datafactoryManagement/lib/models/activityDependency.js, lib/services/datafactoryManagement/lib/models/blobEventsTrigger.js, lib/services/datafactoryManagement/lib/models/factoryGitHubConfiguration.js, lib/services/datafactoryManagement/lib/models/index.d.ts, lib/services/datafactoryManagement/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3561
=> [AutoPR datafactory/resource-manager] [Datafactory] Remove readOnly flag on github hostName property

lib/services/datafactoryManagement/lib/models/azureBlobStorageLinkedService.js, lib/services/datafactoryManagement/lib/models/azureTableStorageLinkedService.js, lib/services/datafactoryManagement/lib/models/index.d.ts, lib/services/datafactoryManagement/lib/models/index.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3331
=> [AutoPR datafactory/resource-manager] add 2 storage linked service type: AzureBlobStorage, AzureTableStorage and support aad auth for AzureBlobStorage

lib/services/apimanagement/lib/models/certificateConfiguration.js, lib/services/apimanagement/lib/models/groupContract.js, lib/services/apimanagement/lib/models/groupContractProperties.js, lib/services/apimanagement/lib/models/groupCreateParameters.js, lib/services/apimanagement/lib/models/groupUpdateParameters.js, lib/services/apimanagement/lib/models/index.d.ts, lib/services/apimanagement/lib/operations/group.js, lib/services/apimanagement/lib/operations/index.d.ts, lib/services/apimanagement/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3609
=> [AutoPR apimanagement/resource-manager] Bug fix on readonly property

lib/services/automationManagement/lib/models/index.d.ts, lib/services/automationManagement/lib/models/sourceControlSyncJob.js, lib/services/automationManagement/lib/models/sourceControlSyncJobById.js, lib/services/automationManagement/lib/models/sourceControlSyncJobStream.js, lib/services/automationManagement/lib/models/sourceControlSyncJobStreamById.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3624
=> [AutoPR automation/resource-manager] Updating SourceControlSyncJobs and SourceControlSyncJobStreams properties and examples. 

lib/services/networkManagement2/lib/models/index.d.ts, lib/services/networkManagement2/lib/models/virtualNetworkGatewayConnection.js, lib/services/networkManagement2/lib/models/virtualNetworkGatewayConnectionListEntity.js, lib/services/networkManagement2/lib/operations/index.d.ts, lib/services/networkManagement2/lib/operations/virtualNetworkGatewayConnections.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3647
=> [AutoPR network/resource-manager] Changes to Support MSEEv2 Datapath for ExpressRoute.

lib/services/batch/lib/models/autoPoolSpecification.js, lib/services/batch/lib/models/cloudJob.js, lib/services/batch/lib/models/cloudJobSchedule.js, lib/services/batch/lib/models/cloudPool.js, lib/services/batch/lib/models/cloudServiceConfiguration.js, lib/services/batch/lib/models/index.d.ts, lib/services/batch/lib/models/jobAddParameter.js, lib/services/batch/lib/models/jobPatchParameter.js, lib/services/batch/lib/models/jobScheduleAddParameter.js, lib/services/batch/lib/models/jobSchedulePatchParameter.js, lib/services/batch/lib/models/jobScheduleUpdateParameter.js, lib/services/batch/lib/models/jobSpecification.js, lib/services/batch/lib/models/jobUpdateParameter.js, lib/services/batch/lib/models/poolAddParameter.js, lib/services/batch/lib/models/poolInformation.js, lib/services/batch/lib/models/poolSpecification.js, lib/services/batch/lib/models/userAccount.js, lib/services/batch/lib/operations/index.d.ts, lib/services/batch/lib/operations/job.js, lib/services/batch/lib/operations/jobSchedule.js, lib/services/batch/lib/operations/pool.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3701
=> [AutoPR batch/data-plane] Update Batch docs

lib/services/automationManagement/lib/operations/dscConfigurationOperations.js, lib/services/automationManagement/lib/operations/index.d.ts
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3749
=> [AutoPR automation/resource-manager] Fixing the spec for DSCConfigurations.

lib/services/networkManagement2/lib/models/azureFirewallIPConfiguration.js, lib/services/networkManagement2/lib/models/index.d.ts
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3743
=> [AutoPR network/resource-manager] Use only PublicIpAddress in Azure Firewall, not both Public and InternalPublic

lib/services/containerRegistryManagement/lib/models/eventContent.js, lib/services/containerRegistryManagement/lib/models/eventRequestMessage.js, lib/services/containerRegistryManagement/lib/models/imageUpdateTrigger.js, lib/services/containerRegistryManagement/lib/models/importImageParameters.js, lib/services/containerRegistryManagement/lib/models/operationDefinition.js, lib/services/containerRegistryManagement/lib/models/operationServiceSpecificationDefinition.js, lib/services/containerRegistryManagement/lib/models/registryListCredentialsResult.js, lib/services/containerRegistryManagement/lib/models/registryPolicies.js, lib/services/containerRegistryManagement/lib/models/registryUpdateParameters.js, lib/services/containerRegistryManagement/lib/models/registryUsageListResult.js, lib/services/containerRegistryManagement/lib/models/sourceProperties.js, lib/services/containerRegistryManagement/lib/models/sourceTrigger.js, lib/services/containerRegistryManagement/lib/models/sourceTriggerUpdateParameters.js, lib/services/containerRegistryManagement/lib/models/sourceUpdateParameters.js, lib/services/containerRegistryManagement/lib/models/taskStepProperties.js, lib/services/containerRegistryManagement/lib/models/taskUpdateParameters.js, lib/services/containerRegistryManagement/lib/models/triggerProperties.js, lib/services/containerRegistryManagement/lib/models/triggerUpdateParameters.js, lib/services/containerRegistryManagement/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3824
=> [AutoPR containerregistry/resource-manager] ACR conf for 2018-09 and Python

lib/services/containerservicesManagement/lib/models/containerServiceDiagnosticsProfile.js, lib/services/containerservicesManagement/lib/models/containerServiceLinuxProfile.js, lib/services/containerservicesManagement/lib/models/containerServiceServicePrincipalProfile.js, lib/services/containerservicesManagement/lib/models/containerServiceSshConfiguration.js, lib/services/containerservicesManagement/lib/models/credentialResults.js, lib/services/containerservicesManagement/lib/models/index.d.ts, lib/services/containerservicesManagement/lib/models/managedCluster.js, lib/services/containerservicesManagement/lib/models/managedClusterUpgradeProfile.js, lib/services/containerservicesManagement/lib/models/orchestratorVersionProfile.js, lib/services/containerservicesManagement/lib/models/orchestratorVersionProfileListResult.js, lib/services/containerservicesManagement/lib/operations/index.d.ts, lib/services/containerservicesManagement/lib/operations/managedClusters.js, lib/services/containerservicesManagement/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3835
=> [AutoPR containerservices/resource-manager] [AKS] note that only one agent pool is currently supported

lib/services/networkManagement2/lib/models/index.d.ts, lib/services/networkManagement2/lib/models/networkInterface.js, lib/services/networkManagement2/lib/operations/index.d.ts, lib/services/networkManagement2/lib/operations/networkInterfaces.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3837
=> [AutoPR network/resource-manager] vtapswaggerupdate

lib/services/authorizationManagement/lib/models/index.d.ts, lib/services/authorizationManagement/lib/models/roleAssignmentCreateParameters.js, lib/services/authorizationManagement/lib/operations/index.d.ts, lib/services/authorizationManagement/lib/operations/roleAssignments.js, lib/services/authorizationManagement/package.json
Created to accumulate context: authorization/resource-manager
=> [AutoPR] authorization/resource-manager

lib/services/networkManagement2/lib/models/index.d.ts, lib/services/networkManagement2/lib/models/interfaceEndpoint.js, lib/services/networkManagement2/lib/models/networkInterface.js, lib/services/networkManagement2/lib/models/subnet.js, lib/services/networkManagement2/lib/operations/index.d.ts, lib/services/networkManagement2/lib/operations/interfaceEndpoints.js, lib/services/networkManagement2/lib/operations/networkInterfaceTapConfigurations.js, lib/services/networkManagement2/lib/operations/networkInterfaces.js, lib/services/networkManagement2/lib/operations/subnets.js, lib/services/networkManagement2/lib/operations/virtualNetworkTaps.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3860
=> [AutoPR network/resource-manager] changes to swagger in interface endpoints and subnet delegation

runtime/ms-rest-azure/lib/credentials/msiTokenCredentials.js
fixes an error trying to parse the expires_on field of the MSI token. actually it always returns 'null'
=> MSI credentials: fix date parsing for expireson token field

lib/services/trafficManagerManagement2/lib/models/endpoint.js, lib/services/trafficManagerManagement2/lib/models/heatMapModel.js, lib/services/trafficManagerManagement2/lib/models/index.d.ts, lib/services/trafficManagerManagement2/lib/models/profile.js, lib/services/trafficManagerManagement2/lib/models/proxyResource.js, lib/services/trafficManagerManagement2/lib/models/resource.js, lib/services/trafficManagerManagement2/lib/models/trackedResource.js, lib/services/trafficManagerManagement2/lib/models/trafficManagerGeographicHierarchy.js, lib/services/trafficManagerManagement2/lib/models/userMetricsModel.js, lib/services/trafficManagerManagement2/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4002
=> [AutoPR trafficmanager/resource-manager] Remove readOnly attribute for ID field of Resource.

lib/services/serviceBusManagement2/lib/models/index.d.ts, lib/services/serviceBusManagement2/lib/models/migrationConfigProperties.js, lib/services/serviceBusManagement2/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4008
=> [AutoPR servicebus/resource-manager] ServiceBus: Added read-only property migrationState to MigrationConfig

lib/services/trafficManagerManagement2/lib/models/endpoint.js, lib/services/trafficManagerManagement2/lib/models/heatMapModel.js, lib/services/trafficManagerManagement2/lib/models/index.d.ts, lib/services/trafficManagerManagement2/lib/models/profile.js, lib/services/trafficManagerManagement2/lib/models/proxyResource.js, lib/services/trafficManagerManagement2/lib/models/resource.js, lib/services/trafficManagerManagement2/lib/models/trackedResource.js, lib/services/trafficManagerManagement2/lib/models/trafficManagerGeographicHierarchy.js, lib/services/trafficManagerManagement2/lib/models/userMetricsModel.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4007
=> [AutoPR trafficmanager/resource-manager] Do not omit type and name while serializing the resource object.

lib/services/websiteManagement2/lib/webSiteManagementClient.d.ts, lib/services/websiteManagement2/lib/webSiteManagementClient.js, lib/services/websiteManagement2/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4010
=> [AutoPR web/resource-manager] Add Microsoft.Web georegions filter parameter LinuxDynamicWorkersEnabled

lib/services/hdInsightManagement/lib/models/cluster.js, lib/services/hdInsightManagement/lib/models/clusterCreateParametersExtended.js, lib/services/hdInsightManagement/lib/models/clusterCreateProperties.js, lib/services/hdInsightManagement/lib/models/clusterGetProperties.js, lib/services/hdInsightManagement/lib/models/index.d.ts, lib/services/hdInsightManagement/lib/models/securityProfile.js, lib/services/hdInsightManagement/lib/operations/clusters.js, lib/services/hdInsightManagement/lib/operations/index.d.ts, lib/services/hdInsightManagement/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4011
=> [AutoPR hdinsight/resource-manager] [HDInsight] Added additional parameters for security profile

runtime/ms-rest-azure/index.d.ts
These parameters are optional because their values are set from environment variables provided by App Service.
=> Define msiEndpoint and msiSecret as optional

lib/services/graphManagement/lib/operations/applications.js, lib/services/graphManagement/lib/operations/groups.js, lib/services/graphManagement/lib/operations/index.d.ts
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4190
=> [AutoPR graphrbac/data-plane] [GraphRBAC] Add delete owner

lib/services/consumptionManagement/lib/consumptionManagementClient.js, lib/services/consumptionManagement/lib/models/index.d.ts, lib/services/consumptionManagement/lib/models/managementGroupAggregatedCostResult.js, lib/services/consumptionManagement/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4069
=> [AutoPR consumption/resource-manager] Introducing New Version 2018-10-01 for Consumption API

lib/services/automationManagement/lib/models/index.d.ts, lib/services/automationManagement/lib/models/sourceControlSyncJob.js, lib/services/automationManagement/lib/models/sourceControlSyncJobById.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4247
=> [AutoPR automation/resource-manager] Updating sync type property from PartialSync to IncrementalSync.

lib/services/resourceManagement/lib/resource/operations/index.d.ts, lib/services/resourceManagement/lib/resource/operations/resourceGroups.js, lib/services/resourceManagement/lib/resource/operations/resources.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4236
=> [AutoPR resources/resource-manager] added descriptions for filter and expand

lib/services/sqlManagement2/lib/models/databaseBlobAuditingPolicy.js, lib/services/sqlManagement2/lib/models/extendedDatabaseBlobAuditingPolicy.js, lib/services/sqlManagement2/lib/models/extendedServerBlobAuditingPolicy.js, lib/services/sqlManagement2/lib/models/index.d.ts, lib/services/sqlManagement2/lib/models/serverBlobAuditingPolicy.js, lib/services/sqlManagement2/lib/operations/databaseBlobAuditingPolicies.js, lib/services/sqlManagement2/lib/operations/databaseVulnerabilityAssessmentScans.js, lib/services/sqlManagement2/lib/operations/extendedDatabaseBlobAuditingPolicies.js, lib/services/sqlManagement2/lib/operations/extendedServerBlobAuditingPolicies.js, lib/services/sqlManagement2/lib/operations/index.d.ts, lib/services/sqlManagement2/lib/operations/serverBlobAuditingPolicies.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4394
=> [AutoPR sql/resource-manager] Update Vulnerability Assessment swaggers

lib/services/networkManagement2/lib/models/flowLogInformation.js, lib/services/networkManagement2/lib/models/index.d.ts, lib/services/networkManagement2/lib/models/trafficAnalyticsConfigurationProperties.js, lib/services/networkManagement2/lib/models/trafficAnalyticsProperties.js, lib/services/networkManagement2/lib/operations/index.d.ts, lib/services/networkManagement2/lib/operations/networkWatchers.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4420
=> [AutoPR network/resource-manager] [Network wathcer] add a new field trafficAnalyticsInterval for TA

lib/services/apimanagement/lib/models/index.d.ts, lib/services/apimanagement/lib/models/userContract.js, lib/services/apimanagement/lib/models/userCreateParameters.js, lib/services/apimanagement/lib/models/userEntityBaseParameters.js, lib/services/apimanagement/lib/models/userUpdateParameters.js, lib/services/apimanagement/lib/operations/index.d.ts, lib/services/apimanagement/lib/operations/user.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4442
=> [AutoPR apimanagement/resource-manager] Remove readonly attribute from identities collection in users

lib/services/storageManagement2/lib/models/index.d.ts, lib/services/storageManagement2/lib/models/storageAccount.js, lib/services/storageManagement2/lib/operations/index.d.ts, lib/services/storageManagement2/lib/operations/storageAccounts.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4457
=> [AutoPR storage/resource-manager] Adds storage account Quick Failover API

lib/services/authorizationManagement/lib/models/index.d.ts, lib/services/authorizationManagement/lib/models/roleAssignment.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4525
=> [AutoPR authorization/resource-manager] Grlin/adding principal typeto ra

lib/services/apimanagement/lib/models/backendBaseParameters.js, lib/services/apimanagement/lib/models/backendContract.js, lib/services/apimanagement/lib/models/backendProperties.js, lib/services/apimanagement/lib/models/backendServiceFabricClusterProperties.js, lib/services/apimanagement/lib/models/backendUpdateParameters.js, lib/services/apimanagement/lib/models/index.d.ts, lib/services/apimanagement/lib/operations/backend.js, lib/services/apimanagement/lib/operations/index.d.ts
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4510
=> [AutoPR apimanagement/resource-manager] typo: Fix apimanagement/resource-manager/Microsoft.ApiManagement/apimbackends.json

lib/services/serviceFabric/lib/models/applicationHealthPolicy.js, lib/services/serviceFabric/lib/models/applicationHealthPolicyMapItem.js, lib/services/serviceFabric/lib/models/applicationUpgradeDescription.js, lib/services/serviceFabric/lib/models/applicationUpgradeProgressInfo.js, lib/services/serviceFabric/lib/models/applicationUpgradeUpdateDescription.js, lib/services/serviceFabric/lib/models/composeDeploymentUpgradeDescription.js, lib/services/serviceFabric/lib/models/composeDeploymentUpgradeProgressInfo.js, lib/services/serviceFabric/lib/models/index.d.ts, lib/services/serviceFabric/lib/models/serviceTypeHealthPolicy.js, lib/services/serviceFabric/lib/models/serviceTypeHealthPolicyMapItem.js, lib/services/serviceFabric/lib/serviceFabricClient.d.ts, lib/services/serviceFabric/lib/serviceFabricClient.js, lib/services/serviceFabric/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4528
=> [AutoPR servicefabric/data-plane] typo: servicefabric/data-plane/Microsoft.ServiceFabric/servicefabric

lib/services/applicationinsights/lib/models/applicationInsightsComponentAvailableFeatures.js, lib/services/applicationinsights/lib/models/applicationInsightsComponentBillingFeatures.js, lib/services/applicationinsights/lib/models/applicationInsightsComponentDataVolumeCap.js, lib/services/applicationinsights/lib/models/applicationInsightsComponentFeature.js, lib/services/applicationinsights/lib/models/applicationInsightsComponentFeatureCapabilities.js, lib/services/applicationinsights/lib/models/applicationInsightsComponentFeatureCapability.js, lib/services/applicationinsights/lib/models/componentPurgeBodyFilters.js, lib/services/applicationinsights/lib/models/index.d.ts, lib/services/applicationinsights/lib/operations/componentCurrentBillingFeatures.js, lib/services/applicationinsights/lib/operations/componentFeatureCapabilities.js, lib/services/applicationinsights/lib/operations/index.d.ts
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4552
=> [AutoPR applicationinsights/resource-manager] typo: applicationinsights/resource-manager/Microsoft.Insights/componentFeaturesAndPricing_API

lib/services/storageManagement2/lib/models/dimension.js, lib/services/storageManagement2/lib/models/index.d.ts, lib/services/storageManagement2/lib/models/listServiceSasResponse.js, lib/services/storageManagement2/lib/models/sKUCapability.js, lib/services/storageManagement2/lib/models/serviceSasParameters.js, lib/services/storageManagement2/lib/models/sku.js, lib/services/storageManagement2/lib/models/storageAccount.js, lib/services/storageManagement2/lib/models/storageAccountCheckNameAvailabilityParameters.js, lib/services/storageManagement2/lib/models/storageAccountCreateParameters.js, lib/services/storageManagement2/lib/models/storageAccountRegenerateKeyParameters.js, lib/services/storageManagement2/lib/models/storageAccountUpdateParameters.js, lib/services/storageManagement2/lib/operations/index.d.ts, lib/services/storageManagement2/lib/operations/storageAccounts.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4549
=> [AutoPR storage/resource-manager] typo: storage/resource-manager/Microsoft.Storage/storage

lib/services/resourceManagement/lib/resource/models/deploymentExtended.js, lib/services/resourceManagement/lib/resource/models/index.d.ts, lib/services/resourceManagement/lib/resource/models/resourceGroup.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4501
=> [AutoPR resources/resource-manager] Add type for DeploymentExtend and ResourceGroup

lib/services/datafactoryManagement/lib/models/blobEventsTrigger.js, lib/services/datafactoryManagement/lib/models/blobTrigger.js, lib/services/datafactoryManagement/lib/models/concurObjectDataset.js, lib/services/datafactoryManagement/lib/models/concurSource.js, lib/services/datafactoryManagement/lib/models/copyActivity.js, lib/services/datafactoryManagement/lib/models/factory.js, lib/services/datafactoryManagement/lib/models/factoryRepoConfiguration.js, lib/services/datafactoryManagement/lib/models/factoryRepoUpdate.js, lib/services/datafactoryManagement/lib/models/hubspotObjectDataset.js, lib/services/datafactoryManagement/lib/models/hubspotSource.js, lib/services/datafactoryManagement/lib/models/index.d.ts, lib/services/datafactoryManagement/lib/models/jiraObjectDataset.js, lib/services/datafactoryManagement/lib/models/jiraSource.js, lib/services/datafactoryManagement/lib/models/paypalObjectDataset.js, lib/services/datafactoryManagement/lib/models/paypalSource.js, lib/services/datafactoryManagement/lib/models/recurrenceScheduleOccurrence.js, lib/services/datafactoryManagement/lib/models/shopifyObjectDataset.js, lib/services/datafactoryManagement/lib/models/shopifySource.js, lib/services/datafactoryManagement/lib/models/squareObjectDataset.js, lib/services/datafactoryManagement/lib/models/squareSource.js, lib/services/datafactoryManagement/lib/models/userProperty.js, lib/services/datafactoryManagement/lib/models/xeroObjectDataset.js, lib/services/datafactoryManagement/lib/models/xeroSource.js, lib/services/datafactoryManagement/lib/operations/factories.js, lib/services/datafactoryManagement/lib/operations/index.d.ts, lib/services/datafactoryManagement/lib/operations/integrationRuntimes.js, lib/services/datafactoryManagement/lib/operations/pipelines.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4573
=> [AutoPR datafactory/resource-manager] typo: datafactory/resource-manager/Microsoft.DataFactory

lib/services/cdnManagement/lib/models/cidrIpAddress.js, lib/services/cdnManagement/lib/models/customDomain.js, lib/services/cdnManagement/lib/models/endpoint.js, lib/services/cdnManagement/lib/models/index.d.ts
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4635
=> [AutoPR cdn/resource-manager] typo: Microsoft.Cdn

lib/services/apimanagement/lib/models/apiManagementServiceBaseProperties.js, lib/services/apimanagement/lib/models/apiManagementServiceResource.js, lib/services/apimanagement/lib/models/apiManagementServiceUpdateParameters.js, lib/services/apimanagement/lib/models/backendReconnectContract.js, lib/services/apimanagement/lib/models/certificateConfiguration.js, lib/services/apimanagement/lib/models/index.d.ts, lib/services/apimanagement/lib/models/reportRecordContract.js, lib/services/apimanagement/lib/models/requestReportRecordContract.js, lib/services/apimanagement/lib/models/subscriptionCreateParameters.js, lib/services/apimanagement/lib/operations/apiDiagnosticLogger.js, lib/services/apimanagement/lib/operations/apiIssue.js, lib/services/apimanagement/lib/operations/apiIssueAttachment.js, lib/services/apimanagement/lib/operations/apiIssueComment.js, lib/services/apimanagement/lib/operations/apiManagementService.js, lib/services/apimanagement/lib/operations/backend.js, lib/services/apimanagement/lib/operations/diagnosticLogger.js, lib/services/apimanagement/lib/operations/index.d.ts, lib/services/apimanagement/lib/operations/property.js, lib/services/apimanagement/lib/operations/reports.js, lib/services/apimanagement/lib/operations/subscription.js, lib/services/apimanagement/lib/operations/tagDescription.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4602
=> [AutoPR apimanagement/resource-manager] Added example for template params

.azure-pipelines/client.test.yml, .azure-pipelines/client.yml, .gitignore, package.json
Pipeline: https://dev.azure.com/azure-sdk/playground/_build?definitionId=31&_a=summary
=> Azure Pipeline for KeyVault

lib/services/automationManagement/lib/models/agentRegistration.js, lib/services/automationManagement/lib/models/dscConfigurationParameter.js, lib/services/automationManagement/lib/models/dscNode.js, lib/services/automationManagement/lib/models/dscNodeConfiguration.js, lib/services/automationManagement/lib/models/dscNodeUpdateParameters.js, lib/services/automationManagement/lib/models/dscNodeUpdateParametersProperties.js, lib/services/automationManagement/lib/models/index.d.ts, lib/services/automationManagement/lib/models/runAsCredentialAssociationProperty.js, lib/services/automationManagement/lib/models/runbookCreateOrUpdateDraftProperties.js, lib/services/automationManagement/lib/models/runbookDraftUndoEditResult.js, lib/services/automationManagement/lib/models/runbookParameter.js, lib/services/automationManagement/lib/models/softwareUpdateConfigurationMachineRun.js, lib/services/automationManagement/lib/models/softwareUpdateConfigurationRun.js, lib/services/automationManagement/lib/models/sourceControlSyncJobById.js, lib/services/automationManagement/lib/models/updateConfiguration.js, lib/services/automationManagement/lib/models/variable.js, lib/services/automationManagement/lib/operations/connectionTypeOperations.js, lib/services/automationManagement/lib/operations/dscNodeOperations.js, lib/services/automationManagement/lib/operations/index.d.ts
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4608
=> [AutoPR automation/resource-manager] typo: Microsoft.Automation

lib/services/databoxManagement/lib/models/dataBoxHeavyAccountCopyLogDetails.js, lib/services/databoxManagement/lib/models/dataBoxHeavyJobDetails.js, lib/services/databoxManagement/lib/models/dataBoxHeavyJobSecrets.js, lib/services/databoxManagement/lib/models/dataBoxHeavySecret.js, lib/services/databoxManagement/lib/models/dataBoxJobDetails.js, lib/services/databoxManagement/lib/models/databoxJobSecrets.js, lib/services/databoxManagement/lib/models/index.d.ts, lib/services/databoxManagement/lib/models/jobDetails.js, lib/services/databoxManagement/lib/models/jobResource.js, lib/services/databoxManagement/lib/operations/index.d.ts, lib/services/databoxManagement/lib/operations/jobs.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4672
=> [AutoPR databox/resource-manager] typo: Microsoft.DataBox

lib/services/devTestLabs/lib/models/attachNewDataDiskOptions.js, lib/services/devTestLabs/lib/models/attachNewDataDiskOptionsFragment.js, lib/services/devTestLabs/lib/models/dataDiskProperties.js, lib/services/devTestLabs/lib/models/dataDiskPropertiesFragment.js, lib/services/devTestLabs/lib/models/disk.js, lib/services/devTestLabs/lib/models/diskFragment.js, lib/services/devTestLabs/lib/models/index.d.ts, lib/services/devTestLabs/lib/operations/disks.js, lib/services/devTestLabs/lib/operations/index.d.ts, lib/services/devTestLabs/lib/operations/notificationChannels.js, lib/services/devTestLabs/lib/operations/virtualMachines.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4685
=> [AutoPR devtestlabs/resource-manager] typo: Microsoft.DevTestLab

lib/services/consumptionManagement/lib/models/budget.js, lib/services/consumptionManagement/lib/models/index.d.ts, lib/services/consumptionManagement/lib/models/proxyResource.js, lib/services/consumptionManagement/lib/models/reservationDetail.js, lib/services/consumptionManagement/lib/models/reservationRecommendation.js, lib/services/consumptionManagement/lib/models/reservationSummary.js, lib/services/consumptionManagement/lib/operations/budgets.js, lib/services/consumptionManagement/lib/operations/index.d.ts, lib/services/consumptionManagement/lib/operations/marketplaces.js, lib/services/consumptionManagement/lib/operations/reservationRecommendations.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4660
=> [AutoPR consumption/resource-manager] typo: Microsoft.Consumption

lib/services/cognitiveServicesManagement/README.md, lib/services/cognitiveServicesManagement/lib/models/checkSkuAvailabilityParameter.js, lib/services/cognitiveServicesManagement/lib/models/checkSkuAvailabilityResult.js, lib/services/cognitiveServicesManagement/lib/models/checkSkuAvailabilityResultList.js, lib/services/cognitiveServicesManagement/lib/models/cognitiveServicesAccount.js, lib/services/cognitiveServicesManagement/lib/models/cognitiveServicesAccountCreateParameters.js, lib/services/cognitiveServicesManagement/lib/models/cognitiveServicesAccountEnumerateSkusResult.js, lib/services/cognitiveServicesManagement/lib/models/cognitiveServicesAccountKeys.js, lib/services/cognitiveServicesManagement/lib/models/cognitiveServicesAccountListResult.js, lib/services/cognitiveServicesManagement/lib/models/cognitiveServicesAccountUpdateParameters.js, lib/services/cognitiveServicesManagement/lib/models/cognitiveServicesResourceAndSku.js, lib/services/cognitiveServicesManagement/lib/models/errorBody.js, lib/services/cognitiveServicesManagement/lib/models/errorModel.js, lib/services/cognitiveServicesManagement/lib/models/index.d.ts, lib/services/cognitiveServicesManagement/lib/models/metricName.js, lib/services/cognitiveServicesManagement/lib/models/operationDisplayInfo.js, lib/services/cognitiveServicesManagement/lib/models/operationEntity.js, lib/services/cognitiveServicesManagement/lib/models/operationEntityListResult.js, lib/services/cognitiveServicesManagement/lib/models/regenerateKeyParameters.js, lib/services/cognitiveServicesManagement/lib/models/resourceSku.js, lib/services/cognitiveServicesManagement/lib/models/resourceSkuRestrictionInfo.js, lib/services/cognitiveServicesManagement/lib/models/resourceSkuRestrictions.js, lib/services/cognitiveServicesManagement/lib/models/resourceSkusResult.js, lib/services/cognitiveServicesManagement/lib/models/sku.js, lib/services/cognitiveServicesManagement/lib/models/usage.js, lib/services/cognitiveServicesManagement/lib/models/usagesResult.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4657
=> [AutoPR cognitiveservices/resource-manager] typo: Microsoft.CognitiveServices

lib/services/notificationHubsManagement/lib/models/apnsCredential.js, lib/services/notificationHubsManagement/lib/models/checkAvailabilityResult.js, lib/services/notificationHubsManagement/lib/models/errorResponse.js, lib/services/notificationHubsManagement/lib/models/index.d.ts, lib/services/notificationHubsManagement/lib/models/mpnsCredential.js, lib/services/notificationHubsManagement/lib/models/notificationHubCreateOrUpdateParameters.js, lib/services/notificationHubsManagement/lib/models/notificationHubPatchParameters.js, lib/services/notificationHubsManagement/lib/models/notificationHubResource.js, lib/services/notificationHubsManagement/lib/models/pnsCredentialsResource.js, lib/services/notificationHubsManagement/lib/operations/index.d.ts, lib/services/notificationHubsManagement/lib/operations/namespaces.js, lib/services/notificationHubsManagement/lib/operations/notificationHubs.js, lib/services/notificationHubsManagement/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4722
=> [AutoPR notificationhubs/resource-manager] typo: notificationhubs/resource-manager/Microsoft.NotificationHubs

lib/services/hanaonazureManagement/lib/models/hanaInstance.js, lib/services/hanaonazureManagement/lib/models/hardwareProfile.js, lib/services/hanaonazureManagement/lib/models/index.d.ts
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4773
=> [AutoPR hanaonazure/resource-manager] Update HanaOnAzure Swagger to support new SKU: S96

lib/services/resourceManagement/lib/policy/models/errorResponse.js, lib/services/resourceManagement/lib/policy/models/index.d.ts
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4831
=> [AutoPR resources/resource-manager] typo: resources/resource-manager/Microsoft.Authorization

lib/services/websiteManagement2/lib/models/appServiceCertificateCollection.js, lib/services/websiteManagement2/lib/models/appServiceCertificateOrderCollection.js, lib/services/websiteManagement2/lib/models/domainAvailablilityCheckResult.js, lib/services/websiteManagement2/lib/models/index.d.ts, lib/services/websiteManagement2/lib/operations/appServiceCertificateOrders.js, lib/services/websiteManagement2/lib/operations/index.d.ts
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4814
=> [AutoPR web/resource-manager] typo: web/resource-manager/Microsoft.DomainRegistration

lib/services/visualSearch/lib/models/imageKnowledge.js, lib/services/visualSearch/lib/models/imageObject.js, lib/services/visualSearch/lib/models/index.d.ts, lib/services/visualSearch/lib/models/query.js, lib/services/visualSearch/lib/models/thing.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4829
=> [AutoPR cognitiveservices/data-plane/VisualSearch] typo: cognitiveservices/data-plane/VisualSearch

lib/services/sqlManagement2/lib/models/index.d.ts, lib/services/sqlManagement2/lib/models/managedDatabase.js, lib/services/sqlManagement2/lib/models/managedDatabaseUpdate.js, lib/services/sqlManagement2/lib/operations/index.d.ts, lib/services/sqlManagement2/lib/operations/managedDatabases.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4907
=> [AutoPR sql/resource-manager] Updating managed database swagger

lib/services/authorizationManagement/lib/models/index.d.ts, lib/services/authorizationManagement/lib/models/roleAssignment.js, lib/services/authorizationManagement/lib/models/roleAssignmentCreateParameters.js, lib/services/authorizationManagement/lib/models/roleAssignmentFilter.js, lib/services/authorizationManagement/lib/operations/index.d.ts, lib/services/authorizationManagement/lib/operations/roleAssignments.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4886
=> [AutoPR authorization/resource-manager] typo: authorization/resource-manager/Microsoft.Authorization

lib/services/containerRegistryManagement/lib/models/dockerBuildRequest.js, lib/services/containerRegistryManagement/lib/models/encodedTaskRunRequest.js, lib/services/containerRegistryManagement/lib/models/fileTaskRunRequest.js, lib/services/containerRegistryManagement/lib/models/iPRule.js, lib/services/containerRegistryManagement/lib/models/index.d.ts, lib/services/containerRegistryManagement/lib/models/index.js, lib/services/containerRegistryManagement/lib/models/networkRuleSet.js, lib/services/containerRegistryManagement/lib/models/registry.js, lib/services/containerRegistryManagement/lib/models/registryUpdateParameters.js, lib/services/containerRegistryManagement/lib/models/sourceProperties.js, lib/services/containerRegistryManagement/lib/models/sourceTrigger.js, lib/services/containerRegistryManagement/lib/models/sourceTriggerUpdateParameters.js, lib/services/containerRegistryManagement/lib/models/sourceUpdateParameters.js, lib/services/containerRegistryManagement/lib/operations/index.d.ts, lib/services/containerRegistryManagement/lib/operations/registries.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4820
=> [AutoPR containerregistry/resource-manager] [ACR] Add Helm actions to webhook

lib/services/resourceManagement/lib/link/operations/index.d.ts, lib/services/resourceManagement/lib/link/operations/resourceLinks.js, lib/services/resourceManagement/lib/models/errorResponse.js, lib/services/resourceManagement/lib/models/index.d.ts, lib/services/resourceManagement/lib/policy/models/errorResponse.js, lib/services/resourceManagement/lib/policy/models/index.d.ts, lib/services/resourceManagement/lib/resource/models/deploymentExtended.js, lib/services/resourceManagement/lib/resource/models/deploymentPropertiesExtended.js, lib/services/resourceManagement/lib/resource/models/deploymentValidateResult.js, lib/services/resourceManagement/lib/resource/models/index.d.ts, lib/services/resourceManagement/lib/resource/models/parametersLink.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4760
=> [AutoPR resources/resource-manager] typo: resources/resource-manager/Microsoft.Solutions

lib/services/containerservicesManagement/lib/operations/index.d.ts, lib/services/containerservicesManagement/lib/operations/managedClusters.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4937
=> [AutoPR containerservices/resource-manager] [AKS]: SP/AAD update operation for 2018-03-31 and 2018-08-01-preview

lib/services/storageManagement2/lib/models/customDomain.js, lib/services/storageManagement2/lib/models/index.d.ts, lib/services/storageManagement2/lib/models/storageAccount.js, lib/services/storageManagement2/lib/models/storageAccountCreateParameters.js, lib/services/storageManagement2/lib/models/storageAccountUpdateParameters.js, lib/services/storageManagement2/lib/operations/index.d.ts, lib/services/storageManagement2/lib/operations/storageAccounts.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4938
=> [AutoPR storage/resource-manager] [Storage] Fix the UseSubDomainName

lib/services/datafactoryManagement/LICENSE.txt, lib/services/datafactoryManagement/lib/models/executeSSISPackageActivity.js, lib/services/datafactoryManagement/lib/models/index.d.ts, lib/services/datafactoryManagement/lib/models/sSISPackageLocation.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4939
=> [AutoPR datafactory/resource-manager] [Azure Data Factory] Change Ssis activity property type to support expression

lib/services/containerservicesManagement/LICENSE.txt, lib/services/containerservicesManagement/lib/operations/managedClusters.js, lib/services/containerservicesManagement/lib/operations/openShiftManagedClusters.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4979
=> [AutoPR containerservices/resource-manager] [AKS] add empty resource group validation

lib/services/cognitiveServicesManagement/LICENSE.txt, lib/services/cognitiveServicesManagement/lib/models/cognitiveServicesAccount.js, lib/services/cognitiveServicesManagement/lib/models/index.d.ts
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5035
=> [AutoPR cognitiveservices/resource-manager] Adding customSubDomainName property.

lib/services/websiteManagement2/LICENSE.txt, lib/services/websiteManagement2/lib/models/corsSettings.js, lib/services/websiteManagement2/lib/models/index.d.ts, lib/services/websiteManagement2/lib/models/networkFeatures.js, lib/services/websiteManagement2/lib/models/site.js, lib/services/websiteManagement2/lib/models/siteAuthSettings.js, lib/services/websiteManagement2/lib/models/siteConfig.js, lib/services/websiteManagement2/lib/models/siteConfigResource.js, lib/services/websiteManagement2/lib/models/sitePatchResource.js, lib/services/websiteManagement2/lib/models/stackMajorVersion.js, lib/services/websiteManagement2/lib/models/vnetInfo.js, lib/services/websiteManagement2/lib/operations/index.d.ts
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5062
=> [AutoPR web/resource-manager] typo: web/resource-manager/Microsoft.Web/stable/2018-02-01/WebApps.json

lib/services/hanaonazureManagement/lib/models/hanaInstance.js, lib/services/hanaonazureManagement/lib/models/index.d.ts
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5107
=> [AutoPR hanaonazure/resource-manager] Add new field 'proximityPlacementGroup' to properties of HanaInstance

lib/services/sqlManagement2/lib/models/index.d.ts, lib/services/sqlManagement2/lib/models/managedInstance.js, lib/services/sqlManagement2/lib/models/managedInstanceUpdate.js, lib/services/sqlManagement2/lib/operations/index.d.ts, lib/services/sqlManagement2/lib/operations/managedInstances.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5114
=> [AutoPR sql/resource-manager] Update managedInstances.json

lib/services/recoveryServicesBackupManagement/lib/models/backupStatusResponse.js, lib/services/recoveryServicesBackupManagement/lib/models/index.d.ts, lib/services/recoveryServicesBackupManagement/lib/models/preValidateEnableBackupRequest.js, lib/services/recoveryServicesBackupManagement/lib/operations/index.d.ts, lib/services/recoveryServicesBackupManagement/lib/operations/protectionIntentOperations.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5133
=> [AutoPR recoveryservicesbackup/resource-manager] Fixing a minor bug in Recovery Services (Backup) 

lib/services/securityManagement/lib/models/alert.js, lib/services/securityManagement/lib/models/index.d.ts
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4902
=> [AutoPR security/resource-manager] Adding new api-version to Microsoft.Security Alerts resource

lib/services/containerservicesManagement/lib/models/index.d.ts, lib/services/containerservicesManagement/lib/models/managedCluster.js, lib/services/containerservicesManagement/lib/operations/index.d.ts, lib/services/containerservicesManagement/lib/operations/managedClusters.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5150
=> [AutoPR containerservice/resource-manager] Revert "[AKS] add apiServerAuthorizedIPRanges property"

lib/services/keyVaultManagement/LICENSE.txt, lib/services/keyVaultManagement/lib/models/index.d.ts, lib/services/keyVaultManagement/lib/models/vault.js, lib/services/keyVaultManagement/lib/models/vaultCreateOrUpdateParameters.js, lib/services/keyVaultManagement/lib/models/vaultProperties.js, lib/services/keyVaultManagement/lib/operations/index.d.ts, lib/services/keyVaultManagement/lib/operations/vaults.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5172
=> [AutoPR keyvault/resource-manager] add description of access policies required condition

lib/services/securityInsightManagement/lib/models/accountEntity.js, lib/services/securityInsightManagement/lib/models/hostEntity.js, lib/services/securityInsightManagement/lib/models/index.d.ts, lib/services/securityInsightManagement/lib/models/officeConsent.js, lib/services/securityInsightManagement/lib/operations/index.d.ts, lib/services/securityInsightManagement/lib/operations/productSettings.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5205
=> [AutoPR securityinsights/resource-manager] typo: securityinsights/resource-manager/Microsoft.SecurityInsights

lib/services/hanaonazureManagement/lib/models/hanaInstance.js, lib/services/hanaonazureManagement/lib/models/index.d.ts
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5196
=> [AutoPR hanaonazure/resource-manager] Add hwRevision field to HanaInstance definition

lib/services/containerservicesManagement/lib/models/containerServiceNetworkProfile.js, lib/services/containerservicesManagement/lib/models/index.d.ts, lib/services/containerservicesManagement/lib/models/managedCluster.js, lib/services/containerservicesManagement/lib/operations/index.d.ts, lib/services/containerservicesManagement/lib/operations/managedClusters.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5286
=> [AutoPR containerservice/resource-manager] including apiServerAuthorizedIPRanges

lib/services/recoveryServicesSiteRecoveryManagement/lib/models/a2ARecoveryPointDetails.js, lib/services/recoveryServicesSiteRecoveryManagement/lib/models/index.d.ts
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5307
=> [AutoPR recoveryservicessiterecovery/resource-manager] [Hub Generated] Review request for Microsoft.RecoveryServices to add version 2018-07-10

lib/services/networkManagement2/lib/models/expressRouteCircuit.js, lib/services/networkManagement2/lib/models/expressRouteCircuitSku.js, lib/services/networkManagement2/lib/models/index.d.ts, lib/services/networkManagement2/lib/operations/expressRouteCircuits.js, lib/services/networkManagement2/lib/operations/index.d.ts
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5317
=> [AutoPR network/resource-manager] Add support for Local Sku

lib/services/serviceBus/lib/servicebusservice.js, lib/services/serviceBus/lib/servicebusservicebase.js
This pr removes hard coded string “servicebus.windows.net” and add host name.
Some methods(delete, unlock etc) fails for china users because the string “servicebus.windows.net” is hardcoded and used in substring operations, so it forms bad url for china users.
=> Remove hard coded string “servicebus.windows.net” and use host name

lib/services/serviceBus/lib/notificationhubservice.js
Existing documentation describes the installation parameter as a string. It is actually an installation object.
The correct parameter can be in seen in the [Notification Hub REST API Documentation ](https://docs.microsoft.com/en-us/previous-versions/azure/reference/mt621153(v%3dazure.100)#request-body)
You can see evidence that it's an object [here ](https://github.com/Azure/azure-sdk-for-node/blob/1f7ddb946a5537c43a576d3842867d12b78d80cf/lib/services/serviceBus/lib/notificationhubservice.js#L512) or in the screenshot below:
I have tested this in my own application and have confirmed that the parameter described in the REST API Documentation is the correct one.
I have also created a [pull request](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32166) to update the type used in …
=> Update createOrUpdateInstallation documentation

lib/services/serviceBus/lib/servicebusservice.js
=> Add method to get queue's dead letter queue

README.md
Key changes now that https://www.npmjs.com/package/azure is pointing to this readme
- Move benefits of new packages up
- Remove the note on the benefits of using the `azure` package which is now deprecated
- Add notes on counterparts in the new world
=> Readme updates regarding new libraries

lib/common/lib/services/serviceclient.js
tunnel proxy use proxyauth attribute and not auth (that is given by url.prase)
without this fix, setting a proxy to any azure http service (like service bus) with username and password will fail
=> Fix proxy with credentials

lib/services/billingManagement/README.md
On line 28 we initiate a client by calling `BillingManagementClient`. However, we import BillingManagement. Update this to be consistent with the call we make.
=> use right class name for import

runtime/ms-rest/Changelog.md, runtime/ms-rest/lib/webResource.js, runtime/ms-rest/package.json, runtime/ms-rest/test/testlist.txt, runtime/ms-rest/test/webResourceTests.js
Currently, there are specs included parameter name with dash (-) , but ms-rest could not process correctly   the url with segments that contains dash , that  will caused the oav  failed  when swagger reviewing  , because the oav use ms-rest to generate a http-request from an example json file
an example specs:
[KeyVault](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/keyvault/data-plane/Microsoft.KeyVault/stable/7.0/keyvault.json#L82)
=> ms-rest need to support dash to the parameter name in path template

lib/services/keyVault/README.md
According to this file: https://raw.githubusercontent.com/Azure/azure-sdk-for-node/master/lib/services/keyVault/lib/keyVaultClient.js
The latest version supports 7.0
=> Update REST API Version being used in azure-keyvault

lib/services/keyVault/README.md
It took me a while to figure out what was going on here: https://github.com/Azure/azure-sdk-for-node/issues/5153
From what was concluded in that issue, this PR shows that `azure-keyvault` only supports `ms-rest-azure` version 2.6.0, and it recommends authenticating with `KeyvaultCredentials`, either the one exported by this package (`azure-keyvault`), or the one that comes with `ms-rest-azure` version 2.6.0, while also stating that other authentication methods from `ms-rest-azure` version 2.6.0 are supported.
=> [azure-keyvault] Mentioning the ms-rest-azure requirements

lib/common/lib/util/atomhandler.js, lib/common/lib/util/js2xml.js, lib/common/package.json, package.json
This is PR is trying to fix issue https://github.com/Azure/azure-sdk-for-node/issues/5159
=> try fix xml builder

lib/services/serviceBus/README.md, lib/services/serviceBus/lib/servicebusserviceclient.js, lib/services/serviceBus/package.json, package.json, runtime/ms-rest-azure/package.json
As per issue #5207 we have an issue with SNAT exhaustion as the behavior of the request library we use does not set the keep alive nor the max number of sockets allowed.  This PR allows the two values of `keepAlive` and `maxSockets` to be set through the `ServiceBusServiceClient.prototype.setAgentOptions` method.
This is then used to override the behavior in `ServiceBusServiceClient.prototype._buildRequestOptions` to override the `callback` parameter to add the two properties to the `requestOptions` to modify the behavior of the request going to the `request` module.
=> Updating Azure-SB with Agent-Options and Keep-Alive behavior

test/testlistarm.txt
Looks like the keyvault tests are running in live mode instead of playback in CI and hence causing failures.
=> Adding keyvault tests in the end

.azure-pipelines/client.yml, package.json, runtime/ms-rest-azure/Changelog.md, runtime/ms-rest-azure/package.json, runtime/ms-rest-azure/test/package.json
=> resolve-ms-rest-azure-security-issue

lib/services/serviceBus/README.md
Adds language that there are other packages for using both @azure/service-bus and @azure/notification-hubs instead of azure-sb.
=> [notification hubs] Add language for @azure/notification-hubs
