- lib/services/monitoring/lib/eventsClient.js
caller is missing in response. this is affecting azure group log show command, where caller is returned as empty
> Add caller to event list response

- tasks/publishall.sh
> Add publish all packages bash script

- lib/services/networkManagement2/lib/networkResourceProviderClient.js
- lib/services/networkManagement2/package.json
Adding Idns on nic,
rename DnsSettings to NetworkInterfaceDnsSettings
> add Idns on Nic

- lib/services/authorizationManagement/lib/authorizationManagementClient.js
- lib/services/authorizationManagement/package.json
Updated sdk for node from hydra specs.
> new version of authorization management

- lib/services/monitoring/package.json
update monitoring package json to 0.10.2
> update monitoring package json to 0.10.2

- test/recordings/keyVault-key-tests.nock.js
- test/services/keyVault/keyVault-key-tests.js
- test/services/keyVault/kv-test-utils.js
Hot fix for indeterminate keyvault test failures. Also enabled testing RSA-HSM key imports.
> Fix keyvault tests

- lib/services/resourceManagement/lib/resourceManagementClient.js
- lib/services/resourceManagement/package.json
Update ARM node sdk to include deployment delete and provider metadata operations
> Update ARM node sdk to include deployment delete and provider metadata operations

- lib/services/resourceManagement/lib/resourceManagementClient.js
- lib/services/resourceManagement/package.json
My changes are just to update the version for provider operations get and list from "2015-07-01-preview" to "2015-07-01" from hydra specs. All other changes are not related to my code.
> Updating provider operations version in node sdk

- lib/services/extra/lib/graphRbacManagementClient.js
- lib/services/extra/package.json
Needed to improve display of role assignments in xplat/posh
> Update Graph client to read additional properties for ADObject from Graph

- lib/services/networkManagement2/lib/networkResourceProviderClient.js
- lib/services/networkManagement2/package.json
Vm scale set changes and outboundNatrule
> Vm scale set changes and outboundNatrule

- lib/services/networkManagement2/lib/networkResourceProviderClient.js
- lib/services/networkManagement2/package.json
Add specs for
ExpressRouteCircuit
Peering
Authorization
Get calls for expressouteServiceProvider, ARP, Routes, Stats tables
minor change in GET NIC
> ExpressRoute changes

- lib/services/authorizationManagement/lib/authorizationManagementClient.js
- lib/services/authorizationManagement/package.json
Update Authorization sdk to include role definition by name filter
> Role filter branch

- lib/services/insights/lib/insightsClient.js
- lib/services/insights/lib/insightsManagementClient.js
- lib/services/insights/package.json
This package is needed for the next release of the CLI for Insights
> Update insights to latest hydra spec

- lib/services/dataLake.Analytics/lib/dataLakeAnalyticsCatalogManagementClient.js
- lib/services/dataLake.Analytics/lib/dataLakeAnalyticsJobManagementClient.js
- lib/services/dataLake.Analytics/package.json
- lib/services/dataLake.Store/lib/dataLakeStoreFileSystemManagementClient.js
- lib/services/dataLake.Store/package.json
Update catalog to include new types
Update filesystem to remove internal* functions
update job to have the correct version suffix.
> Updates for catalog and filesystem

- lib/services/dataLake.Analytics/README.md
- lib/services/dataLake.Analytics/package.json
- lib/services/dataLake.Store/README.md
- lib/services/dataLake.Store/lib/dataLakeStoreFileSystemManagementClient.js
- lib/services/dataLake.Store/package.json
we have three functions that should not follow redirects. Fixing those
so that they don't.
Also adding the completed README documentation from our PM and Doc team.
> Update readme and remove follow redirect

- lib/services/authorizationManagement/lib/authorizationManagementClient.js
- lib/services/authorizationManagement/package.json
Latest generated code from Authorization hydra specs.
Updated version to 2.0.0
> Authorization sdk update 

- lib/services/dataLake.Analytics/README.md
- lib/services/dataLake.Analytics/package.json
this only lists jobs, it doesn't submit one, so changing the
documentation to reflect that.
> Update the readme to be more accurate

- lib/services/dataLake.Analytics/lib/dataLakeAnalyticsJobManagementClient.js
- lib/services/dataLake.Analytics/package.json
This enables structured error messages for jobs.
> Update to the Job Management API

- lib/services/networkManagement2/lib/models/index.d.ts
- lib/services/networkManagement2/lib/models/outboundNatRule.js
- lib/services/networkManagement2/lib/models/publicIPAddress.js
- lib/services/networkManagement2/lib/models/subnet.js
[DO NOT MERGE] I still need to send the Net SDK
> [DO NOT MERGE]fix required properties

- lib/services/networkManagement2/generate.cmd
- lib/services/networkManagement2/lib/models/inboundNatRule.js
- lib/services/networkManagement2/lib/models/index.d.ts
InboundNATRule updated
@DeepakRajendranMsft @amarzavery
> ARM Networking: generating from latest spec

- lib/services/extra/lib/graphRbacManagementClient.js
- lib/services/extra/package.json
- Autogenerated sdk node for AD Application command updates.
- Version modified to 0.2.12 from 0.1.12
> Azure AD Application commands update

- examples/blog/blog.js
- examples/blog/package.json
- examples/blog/server.js
- examples/blog/views/blog_new.ejs
- examples/blog/views/blog_show.ejs
- examples/blog/views/index.ejs
- examples/blog/views/layout.ejs
- update to Express 4.*
- update to latest Azure module version
- dependcy updates
- rewrite of syntax and implementation both
of server code and Azure related code
- add new example of using batch processes
- add examples of using entity generators
- update html templates markup
- use HTML5 markup in templates
- fix UI problems in markup
- and other fixes and updates
Thanks!
Note that this PR depends on fix for: #1590 which is already covered by #1591 
Otherwise please patch `azure` module when testing this PR.
Thanks!
> :art: Update by rewrite Blog example

- examples/geophoto/README.md
- examples/geophoto/config.default.json
- examples/geophoto/controllers/pushpinController.js
- examples/geophoto/package.json
- examples/geophoto/public/scripts/geophoto.js
- examples/geophoto/public/stylesheets/style.css
- examples/geophoto/server.js
- examples/geophoto/services/pushpinService.js
- examples/geophoto/views/index.ejs
- examples/geophoto/views/layout.ejs
- examples/geophoto/views/setup.ejs
This commit updates geophoto (aka Pushpins) application
by complete rewrite of its implementation while retaining
all existing features (and adding some nice touches to them)
- update to latest Azure SDK module version
- rewrite all Azure SDK syntax to newest version
- update dependencies
- rewrite server implementation to Express 4.*
- update HTML markup to HTML5
- add some HTML5 enhancement features e.g. for forms
- improve logic for blog and entities
- add support for handing image/* mimetypes as intended
- verify index/create actions
- verify upload/delete/clear actions
- add small README to explain how to run example
- some code unification and fixes (styles, quotes, etc)
This commit was tested using Node 4.2.4 LST on Mac OS X.
Thanks!
> :art: Update geophoto application example

- examples/tasklist/home.js
- examples/tasklist/package.json
- examples/tasklist/server.js
- examples/tasklist/views/home.ejs
- examples/tasklist/views/home.jade
This commit updates tasklist example:
Express 4.* migration
migration of Azure module API usage to current version
templates updates and rendering fixes
markup update in templates to HTML5
Note: This PR depends on fix #1587. If you are testing it locally please make sure to apply patch from #1587 to lib/azure.js.
Thanks!
> :art: Update via rewrite tasklist example [resubmitted]

- examples/samples/continuationsample.js
This commit updates:
- Azure SDK syntax and implementation to current version
- add some minor changes in code implementation
- fix formatting and white space
When run example will output:
```
Created the container: false
Created 50 blobs.
There are 50 blobs in this page.
Listing blob in pages completed.
```
Thanks!
> :art: Update continuationsample

- examples/samples/leaseblobsample.js
This commit updates lease code examples to use
latest version of Azure SDK syntax:
- update implementation to latest version
- use *IfNotExists* where application
- use documented arguments in callbacks as used
in Azure documentation website (error/result/response)
- remove Node deprecated api and replace with update ones
- some other small code changes like formatting, white-space, etc
When run example outputs:
```
node leaseblobsample.js
Created the container leasesample
Created the blob leasesample
Worker acquired the lease whose ID is
cd721937-65ec-4905-9e5b-a8ce891b9422
Worker renewed the lease whose ID is
cd721937-65ec-4905-9e5b-a8ce891b9422
```
The other client outputs:
```
node leaseblobsample.js
Created the container leasesample
Created the blob leasesample
Worker failed in …
```
> :art: Upate Blob lease sample

- examples/samples/blobuploaddownloadsample.js
This commit updates Blob upload/download sample to
latest version of Azure SDK:
- Azure SDK syntax and implementation reviewed and changed
- remove deprecated Node api and replace with other methods
- use cleaner callback implementation and full, documented
argument names from Azure SDK
- remove unused declarations
- some other small fixes, like code cleanup, white space, etc
The sample when run outputs:
```
node blobuploaddownloadsample.js
"/Users/piotrblazejewicz/development/source/"
"/Users/piotrblazejewicz/development/target/" "delete"
Created the container updownsample
Blob .deployment upload finished.
Blob .yo-rc.json upload finished.
Blob .editorconfig upload finished.
Blob deploy.cmd upload finished.
Blob .gitignore upload finished.
Blob jsconfig.json upload finished.
Blob …
```
> :art: Update blob upload/download sample

- examples/samples/sbtopic.js
This commit updates sbtopic.js example to use
latest Azure SDK version:
- update syntax where applicable
- write cleaner callbacks for Azure SDK calls
where applicable (e.g. we care only about messages
not errors)
- remove deprecated or unused api references
- update implementation for native Node api
- small fixes in syntax, formatting, white space, etc
When run example will output:
```
> node sbtopic.js
Created the topic topicsample
Sent first Message
Sent Second Message
Send Message Works
Send Message Still Works
Send Message Works
Send Message Still Works
```
Thanks!
> :art: Update Service Bus topics example

- examples/samples/longpolling.js
This commit updates longpolling example
- update some methods implementation to current
SDK version
- more explicit arguments in topic related methods
- remove unused or deprecated methods
- small fixes like white space, formatting ,etc
When run this sample will output:
> node longpolling.js
Created the topic topic_1
Created subscription subscription_1
Message 0 sent
Message received. Content:
message0
Message 1 sent
Message received. Content:
message1
Message 2 sent
Message received. Content:
message2
Thanks!
> :art: Update ServiceBus longpolling sample

- examples/samples/sbqueue.js
- update syntax to current Azure SDK version
- a little cleaner arguments names (a message1 and
message2 are just enough to get idea of FIFO rules)
- smaller code changes including names, formatting and
white space.
When run this sample should output:
```
> node sbqueue.js
Created the queue: false
Sent first Message
Sent Second Message
Send Message Works
Send Message Still Works
```
Thanks!
> :art: Update ServiceBus Queue sample

- gulpfile.js
- lib/services/computeManagement2/lib/models/diskEncryptionSettings.js
- lib/services/computeManagement2/lib/models/index.d.ts
- lib/services/computeManagement2/lib/operations/virtualMachineScaleSets.js
- lib/services/computeManagement2/package.json
@amarzavery 
It doesn't seem like ```0.16.0-Nightly20160316``` fixes the problem of enum parsing & comparison?
> Use AR 0.16.0-Nightly20160316

- lib/services/computeManagement/lib/computeManagementClient.js
- lib/services/computeManagement/package.json
@amarzavery @haocs Could you please help review?
> AzureCP PR: ASM Migration APIs

- lib/services/dataLake.Store/README.md
This update makes the samples in the readme work with the new package that will be published.
> Missed readme update.

- lib/services/keyVaultManagement/README.md
- lib/services/keyVaultManagement/lib/keyVaultManagementClient.js
- lib/services/keyVaultManagement/package.json
-Update the Key Vault management API version
-Update the example code to add the mandatory tenantId parameter and
instructions on using this API in Germany, China, and the US Government
environments
> Update the Key Vault management API version and example code

- lib/services/dataLake.Analytics/lib/job/models/index.d.ts
- lib/services/dataLake.Analytics/lib/job/models/jobResource.js
- lib/services/dataLake.Analytics/package.json
These were found during internal testing and need to be added for this
release.
> Adding additional allowed enums.

- swagger_to_sdk_config.json
Last version of the file:
- Update with projects syntax
- Mode the Header to the meta node to save some line
- Add Batch exceptions
Tested, seems fine: https://github.com/lmazuel/azure-sdk-for-node/commit/47fc1590e8402213f53619f076b7eea25d029cb5
> Last version of SwaggerToSdk configuration file

- lib/services/serviceBus/lib/notificationhubservice.js
- lib/services/serviceBus/package.json
- test/recordings/apnsservice-tests.nock.js
- test/recordings/gcmservice-tests.nock.js
- test/recordings/mpnsservice-tests.nock.js
- test/recordings/notificationhubservice-tests.nock.js
- test/recordings/wnsservice-tests.nock.js
Release 0.10.3 - Fix Api-Version bug in NotificationHub Service calls for SendNotifications.
> Fix Api-Version bug in NotificationHub Service calls for SendNotifications.

- lib/services/batch/package.json
This reverts commit 0d237ad44932246f0050e54ef06759010880a91c.
Realized that this release DOES in fact contain a breaking change like I originally thought it did.  Sorry!
> Revert "Fix Batch npm package version"

- lib/services/webSiteManagement2/lib/models/deletedSite.js
- lib/services/webSiteManagement2/lib/models/index.d.ts
- lib/services/webSiteManagement2/lib/models/site.js
- lib/services/webSiteManagement2/lib/models/siteConfig.js
- lib/services/webSiteManagement2/lib/operations/index.d.ts
- lib/services/webSiteManagement2/lib/operations/sites.js
- lib/services/webSiteManagement2/package.json
> arm-web:refresh for linux support

- lib/services/HDInsight2/lib/hDInsightManagementClient.js
- lib/services/HDInsight2/package.json
This changesets adds a new securityProfile section that will allow
integration of a HDInsight cluster with active directory.
> add securityProfile to create parameters

- lib/services/dataLake.Analytics/README.md
- lib/services/dataLake.Store/README.md
Updating both ADL readme's prior to publish.
> Update ADL readme files, reflecting latest swagger

- lib/services/dataLake.Analytics/lib/account/models/addStorageAccountParameters.js
- lib/services/dataLake.Analytics/lib/account/models/createStorageAccountInfo.js
- lib/services/dataLake.Analytics/lib/account/models/dataLakeAnalyticsAccount.js
- lib/services/dataLake.Analytics/lib/account/models/dataLakeStoreAccountInfo.js
- lib/services/dataLake.Analytics/lib/account/models/index.d.ts
- lib/services/dataLake.Analytics/lib/account/models/listSasTokensResult.js
- lib/services/dataLake.Analytics/lib/account/models/storageAccountInfo.js
- lib/services/dataLake.Analytics/lib/account/operations/account.js
- lib/services/dataLake.Analytics/lib/account/operations/dataLakeStoreAccounts.js
- lib/services/dataLake.Analytics/lib/account/operations/index.d.ts
- lib/services/dataLake.Analytics/lib/account/operations/storageAccounts.js
- lib/services/dataLake.Analytics/package.json
- lib/services/dataLake.Store/lib/filesystem/models/aclStatusResult.js
- lib/services/dataLake.Store/lib/filesystem/models/adlsError.js
- lib/services/dataLake.Store/lib/filesystem/models/adlsFileNotFoundException.js
- lib/services/dataLake.Store/lib/filesystem/models/adlsIOException.js
- lib/services/dataLake.Store/lib/filesystem/models/adlsThrottledException.js
- lib/services/dataLake.Store/lib/filesystem/models/fileStatusProperties.js
- lib/services/dataLake.Store/lib/filesystem/models/fileStatusResult.js
- lib/services/dataLake.Store/lib/filesystem/models/fileStatuses.js
- lib/services/dataLake.Store/lib/filesystem/models/index.d.ts
- lib/services/dataLake.Store/lib/filesystem/models/index.js
- lib/services/dataLake.Store/lib/filesystem/operations/fileSystem.js
- lib/services/dataLake.Store/lib/filesystem/operations/index.d.ts
- lib/services/dataLake.Store/package.json
Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/730
> Automatic PR from RestAPI-PR730

- Documentation/Authentication.md
- README.md
Updated the authentication documentation to better illustrate the various ways to
authenticate in the SDK. Update the samples to use a more idiomatic JavaScript
style.
Added some more detail on how the module is organized and cleaned up the copy so
that people may more easily find the docs and get started. Fixed the formatting
of the table so that the npm install commands show up.
> Documentation updates.

- Extensions/azure-node-essentials/LICENSE.MIT.txt
- Extensions/azure-node-essentials/README.md
- Extensions/azure-node-essentials/changelog.md
- Extensions/azure-node-essentials/extension.js
- Extensions/azure-node-essentials/package.json
1. Made the extension to be robust against some npm errors
2. Polished the source code folder for publishing to vscode marketplace.
> Minor fixes for publishing

- runtime/ms-rest/package.json
.. for useragent change.
This is follow up to #2079 and part of work for #2076
> bump up ms-rest package version..

- runtime/ms-rest-azure/lib/azureServiceClient.js
- runtime/ms-rest-azure/package.json
.. headers. Part of work for issue #2076
This is part 2 of the runtime changes. See #2078 for why runtime changes need to be made independently.
> msrestazure - send user agent info in request..

- runtime/ms-rest-azure/package.json
in dependent package (ms-rest)
> bump up version of ms-rest-azure for useragent fixes

- lib/common/lib/util/constants.js
- lib/services/serviceBus/lib/models/queueresult.js
- lib/services/serviceBus/lib/servicebusservice.js
Related issue: https://github.com/Azure/azure-sdk-for-node/issues/2028
> Service Bus create queue ENABLE_PARTITIONING

- gulpfile.js
except - (ml, monitor rename, mobileEngage). Have questions about them
> updated mappings in gulpfile

- lib/services/serviceBus/README.md
Do not use 'azure' package after installing package 'azure-sb'
> Update ServiceBus README.md, replace 'azure' with 'azure-sb'

- runtime/ms-rest/lib/webResource.js
Requires part of https://github.com/Azure/openapi-validation-tools/issues/76
> Respect the Content-Type provided by user. Do not append anything to it

- lib/services/trafficManagerManagement2/lib/models/dnsConfig.js
- lib/services/trafficManagerManagement2/lib/models/index.d.ts
- lib/services/trafficManagerManagement2/lib/models/monitorConfig.js
- lib/services/trafficManagerManagement2/lib/models/profile.js
- lib/services/trafficManagerManagement2/lib/operations/index.d.ts
- lib/services/trafficManagerManagement2/lib/operations/profiles.js
- lib/services/trafficManagerManagement2/lib/trafficManagerManagementClient.js
- lib/services/trafficManagerManagement2/package.json
Add new settings to the monitorConfig section of Traffic Manager profiles. Support for new API version: 2017-05-01
> Traffic Manager version 2017-05-01 including new monitorConfig settings

- README.md
Just nitpicking as is usual with professors :-)
> Giving uniformity to the documentation

- lib/services/graphManagement/package.json
- package.json
updated the package.json to use the changes from the swagger specs PR
https://github.com/Azure/azure-rest-api-specs/pull/1103
> Generating new package with the api version change for graphrbac

- lib/services/dataLake.Store/package.json
pushing out an update for PR 2148
> patch datalake.store for type definition file update

- package_service_mapping.json
Required file for documentation generation. I Actually scripted the creation of
this so please review it and let me know if anything is obviously borked.
References #2191
> Add package service mapping file.

- package_service_mapping.json
Sorted services alphabetically, cleaned up the names, and removed the
data plane pieces.
> Update service mapping.

- lib/services/batch/README.md
Using [azure-storage](https://www.npmjs.com/package/azure-storage) as an example, updated the README.md to contain a direct link to relevant documentation. (https://raw.githubusercontent.com/Azure/azure-storage-node/master/README.md)
> Added link to API reference

- lib/services/HDInsightJob2/lib/hDInsightJobManagementClient.js
> fix #2232: HDInsight hive job submission parameters error

- runtime/ms-rest-azure/lib/credentials/msiTokenCredentials.js
- runtime/ms-rest-azure/lib/login.js
- runtime/ms-rest-azure/lib/msRestAzure.js
- runtime/ms-rest-azure/package.json
- runtime/ms-rest-azure/test/msiTokenCredentialTests.js
- runtime/ms-rest-azure/test/package.json
- runtime/ms-rest-azure/test/testlist.txt
Basing this PR on top of Amar's AuthFromFile PR which is still open. 
Implementation of this PR is in the following commits: 
1. b1c952d -- implement MSI Token Credentials and add login methods
1. 0cb92a0 -- tests
> MSI Authentication (scope: VMs)

- lib/services/networkManagement2/lib/models/index.d.ts
- lib/services/networkManagement2/lib/models/securityRule.js
- lib/services/networkManagement2/lib/operations/index.d.ts
- lib/services/networkManagement2/lib/operations/securityRules.js
- lib/services/networkManagement2/package.json
Re-generated Network SDK to include this fix https://github.com/Azure/azure-rest-api-specs/pull/1757
> Network SDK update

- lib/services/HDInsight2/lib/hDInsightManagementClient.js
> componentVerions support for HDInsight cluster

- lib/services/schedulerManagement2/lib/models/basicAuthentication.js
- lib/services/schedulerManagement2/lib/models/clientCertAuthentication.js
- lib/services/schedulerManagement2/lib/models/httpAuthentication.js
- lib/services/schedulerManagement2/lib/models/httpRequest.js
- lib/services/schedulerManagement2/lib/models/index.d.ts
- lib/services/schedulerManagement2/lib/models/index.js
- lib/services/schedulerManagement2/lib/models/jobAction.js
- lib/services/schedulerManagement2/lib/models/jobDefinition.js
- lib/services/schedulerManagement2/lib/models/jobErrorAction.js
- lib/services/schedulerManagement2/lib/models/jobProperties.js
- lib/services/schedulerManagement2/lib/models/oAuthAuthentication.js
- lib/services/schedulerManagement2/lib/operations/index.d.ts
- lib/services/schedulerManagement2/lib/operations/jobs.js
- lib/services/schedulerManagement2/package.json
- PR https://github.com/Azure/azure-rest-api-specs/pull/2104
- Fixes https://github.com/Azure/azure-sdk-for-node/issues/2347
> regenerating scheduler client based on the changes to make HttpAuthentication model polymorphic

- runtime/ms-rest/package-lock.json
- runtime/ms-rest/package.json
- runtime/ms-rest/test/serializationTests.js
[Regular Expression Denial of Service](https://nodesecurity.io/advisories/532)
ms-rest@2.3.0 > moment@2.18.1
See #2381
[Prototype pollution attack](https://nodesecurity.io/advisories/566)
ms-rest@2.3.0 > request@2.83.0 > hawk@6.0.2 > hoek@4.2.0
> Update packages to fix NSP issues

- lib/services/marketplaceorderingManagement/lib/models/agreementTerms.js
- lib/services/marketplaceorderingManagement/lib/models/index.d.ts
- lib/services/marketplaceorderingManagement/lib/operations/index.d.ts
- lib/services/marketplaceorderingManagement/lib/operations/marketplaceAgreements.js
- lib/services/marketplaceorderingManagement/package.json
fixes https://github.com/Azure/azure-sdk-for-node/issues/2423
> changing retrieveDatetime to string to avoid losing precision.

- lib/services/serviceBus/lib/notificationhubservice.js
- lib/services/serviceBus/package.json
Adding support to update registration tags
> Adding support for tags update registration

- lib/services/keyVault/lib/keyVault.d.ts
- lib/services/keyVault/package.json
Fixes: https://github.com/Azure/azure-sdk-for-node/issues/2445
Fixes: https://github.com/Azure/azure-sdk-for-node/issues/2440
> keyvault type definition file changes to resolve problems with typescript

- runtime/ms-rest/Changelog.md
- runtime/ms-rest/lib/serialization.js
- runtime/ms-rest/package-lock.json
- runtime/ms-rest/package.json
- runtime/ms-rest/test/serializationTests.js
fixes an issue related to #2452
> ensure that the provided object is a Duration like object.

- lib/services/cdnManagement/lib/cdnManagementClient.d.ts
- lib/services/cdnManagement/lib/cdnManagementClient.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2700
> [AutoPR cdn/resource-manager]  Add example for checkNameAvailability

- lib/services/dataLake.Store/README.md
filesystem property doesn't exist, but fileSystem works for me
> Rename filesystem to fileSystem

- lib/services/apimanagement/lib/apiManagementClient.d.ts
- lib/services/apimanagement/lib/apiManagementClient.js
- lib/services/apimanagement/lib/models/requestReportCollection.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2721
> [AutoPR apimanagement/resource-manager] Fix issue with 2017-03-01 version of api-management

- lib/services/cosmosdbManagement/package.json
Should've been included in #2486
> Bump cosmosdbManagement to 1.1.1-preview

- lib/services/apimanagement/lib/models/requestReportCollection.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2576
> [AutoPR apimanagement/resource-manager] Issues resource with Comments and Attachments subresources were added

- lib/services/batch/package.json
The latest moment version is 2.21.0.
> Change the wrong moment version

- lib/services/monitor/lib/lib/operations/metricAlerts.js
- lib/services/monitor/lib/lib/operations/metricAlertsStatus.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2787
> [AutoPR monitor/resource-manager] Fix bugs (typos) in the swagger

- lib/services/eventgridManagement/LICENSE.txt
- lib/services/eventgridManagement/README.md
- lib/services/eventgridManagement/lib/eventGridManagementClient.d.ts
- lib/services/eventgridManagement/lib/eventGridManagementClient.js
- lib/services/eventgridManagement/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2796
> [AutoPR eventgrid/resource-manager] EventGrid: Initial placeholder for a new preview API version based on previous stable API version

- lib/services/networkManagement2/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2822
> [AutoPR network/resource-manager] Copy App Gateway Examples from 2018-01-01 to 2018-02-01

- lib/services/batch/package-lock.json
- lib/services/batch/package.json
- package.json
- runtime/ms-rest-azure/package.json
- runtime/ms-rest/package-lock.json
- runtime/ms-rest/package.json
Same as https://github.com/Microsoft/appcenter-cli/pull/325 and https://github.com/Microsoft/appcenter-cli/pull/424
If they are in `dependencies`, it enforces packages depends on these packages to install the same packages.
So please add them as `devDependencies.`
> Make @types packages dev dependencies

- lib/services/spellCheck/LICENSE.txt
- lib/services/spellCheck/lib/spellCheckAPIClient.d.ts
- lib/services/spellCheck/lib/spellCheckAPIClient.js
- lib/services/spellCheck/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2859
> [AutoPR cognitiveservices/data-plane/SpellCheck] Change C# SDK namespace

- lib/services/resourceHealthManagement/LICENSE.txt
- lib/services/resourceHealthManagement/README.md
- lib/services/resourceHealthManagement/lib/microsoftResourceHealth.d.ts
- lib/services/resourceHealthManagement/lib/microsoftResourceHealth.js
- lib/services/resourceHealthManagement/lib/models/index.d.ts
- lib/services/resourceHealthManagement/lib/models/operation.js
- lib/services/resourceHealthManagement/lib/models/operationDisplay.js
- lib/services/resourceHealthManagement/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2863
> [AutoPR resourcehealth/resource-manager] Fix swagger violation for resource health operations definitions

- lib/services/automationManagement/lib/models/dscNodeConfigurationCreateOrUpdateParameters.js
- lib/services/automationManagement/lib/models/index.d.ts
- lib/services/automationManagement/lib/models/index.js
- lib/services/automationManagement/lib/operations/dscNodeConfigurationOperations.js
- lib/services/automationManagement/lib/operations/index.d.ts
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2870
> [AutoPR automation/resource-manager] Correcting the NodeConfiguration Model and Example

- lib/services/automationManagement/lib/models/index.d.ts
- lib/services/automationManagement/lib/models/job.js
- lib/services/automationManagement/lib/models/jobCollectionItem.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2905
> [AutoPR automation/resource-manager] Changing enum to free string for Provisioning State

- lib/services/batch/lib/operations/index.d.ts
- lib/services/batch/lib/operations/job.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2930
> [AutoPR batch/data-plane] Batch API: Fix the wrong statement in description

- lib/services/eventgridManagement/lib/models/index.d.ts
- lib/services/eventgridManagement/lib/models/topic.js
- lib/services/eventgridManagement/lib/models/trackedResource.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2956
> [AutoPR eventgrid/resource-manager] EventGrid Py conf to 1.0.0

- lib/services/automationManagement/lib/models/dscConfiguration.js
- lib/services/automationManagement/lib/models/dscConfigurationListResult.js
- lib/services/automationManagement/lib/models/dscNode.js
- lib/services/automationManagement/lib/models/dscNodeConfigurationListResult.js
- lib/services/automationManagement/lib/models/dscNodeListResult.js
- lib/services/automationManagement/lib/models/index.d.ts
- lib/services/automationManagement/lib/models/index.js
- lib/services/automationManagement/lib/models/linuxProperties.js
- lib/services/automationManagement/lib/models/softwareUpdateConfiguration.js
- lib/services/automationManagement/lib/models/sourceControlSyncJob.js
- lib/services/automationManagement/lib/models/sourceControlSyncJobById.js
- lib/services/automationManagement/lib/models/updateConfiguration.js
- lib/services/automationManagement/lib/models/windowsProperties.js
- lib/services/automationManagement/lib/operations/dscConfigurationOperations.js
- lib/services/automationManagement/lib/operations/dscNodeConfigurationOperations.js
- lib/services/automationManagement/lib/operations/dscNodeOperations.js
- lib/services/automationManagement/lib/operations/index.d.ts
- lib/services/automationManagement/lib/operations/softwareUpdateConfigurations.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3009
> [AutoPR automation/resource-manager] Edit property names for SourceControlSyncJob

- lib/services/websiteManagement2/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3086
> [AutoPR web/resource-manager] Update CommonDefinitions.json

- lib/services/keyvault/lib/lib/keyVaultClient.d.ts
- lib/services/keyvault/lib/lib/keyVaultClient.js
- lib/services/keyvault/lib/lib/models/certificateBundle.js
- lib/services/keyvault/lib/lib/models/certificateCreateParameters.js
- lib/services/keyvault/lib/lib/models/certificateImportParameters.js
- lib/services/keyvault/lib/lib/models/certificatePolicy.js
- lib/services/keyvault/lib/lib/models/certificateUpdateParameters.js
- lib/services/keyvault/lib/lib/models/index.d.ts
- lib/services/keyvault/lib/lib/models/keyCreateParameters.js
- lib/services/keyvault/lib/lib/models/keyProperties.js
- lib/services/keyvault/lib/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3104
> [AutoPR keyvault/data-plane] fix typos

- lib/services/customSearch/LICENSE.txt
- lib/services/customSearch/lib/customSearchAPIClient.d.ts
- lib/services/customSearch/lib/customSearchAPIClient.js
- lib/services/customSearch/lib/operations/customInstance.js
- lib/services/customSearch/lib/operations/index.d.ts
- lib/services/customSearch/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3093
> [AutoPR cognitiveservices/data-plane/CustomWebSearch] renaming custom search to custom web search

- lib/services/operationalInsightsManagement/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3142
> [AutoPR operationalinsights/resource-manager] Plug SwaggerToSdk to LogAnalyticsMgmt

- lib/services/networkManagement2/lib/operations/index.d.ts
- lib/services/networkManagement2/lib/operations/virtualNetworkGateways.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3163
> [AutoPR network/resource-manager] reverted methods removal

- lib/services/computeManagement2/lib/models/diskUpdate.js
- lib/services/computeManagement2/lib/models/index.d.ts
- lib/services/computeManagement2/lib/models/index.js
- lib/services/computeManagement2/lib/models/snapshotUpdate.js
- lib/services/computeManagement2/lib/operations/index.d.ts
- lib/services/computeManagement2/lib/operations/snapshots.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3159
> [AutoPR compute/resource-manager] [Disk swagger] Removing resourceUpdate, adding contents to diskupdate and snapshotupdate

- lib/services/containerservicesManagement/lib/models/index.d.ts
- lib/services/containerservicesManagement/lib/models/managedCluster.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3203
> [AutoPR containerservices/resource-manager] [AKS] add nodeResourceGroup property 

- ChangeLog.md
Fixes error mentioned in https://github.com/Azure/azure-sdk-for-node/pull/2967#issuecomment-396967359
> Fix typo in year

- lib/services/containerinstanceManagement/lib/models/containerExecRequest.js
- lib/services/containerinstanceManagement/lib/models/containerExecRequestTerminalSize.js
- lib/services/containerinstanceManagement/lib/models/index.d.ts
- lib/services/containerinstanceManagement/lib/operations/index.d.ts
- lib/services/containerinstanceManagement/lib/operations/startContainer.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3231
> [AutoPR containerinstance/resource-manager] Container Instance - Fix Mistake in June Update

- lib/services/datafactoryManagement/lib/models/integrationRuntimeComputeProperties.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3237
> [AutoPR datafactory/resource-manager] [Data Factory] Remove maximum maxParallelExecutionsPerNode validation

- lib/services/cosmosdbManagement/lib/operations/databaseAccounts.js
- lib/services/cosmosdbManagement/lib/operations/index.d.ts
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3233
> [AutoPR cosmos-db/resource-manager] Cosmos DB - POST operation for retrieving read only keys

- lib/services/logicManagement/lib/operations/agreements.js
- lib/services/logicManagement/lib/operations/index.d.ts
- lib/services/logicManagement/lib/operations/maps.js
- lib/services/logicManagement/lib/operations/partners.js
- lib/services/logicManagement/lib/operations/schemas.js
- lib/services/logicManagement/lib/operations/sessions.js
- lib/services/logicManagement/lib/operations/workflowRunActions.js
- lib/services/logicManagement/lib/operations/workflowRuns.js
- lib/services/logicManagement/lib/operations/workflowTriggerHistories.js
- lib/services/logicManagement/lib/operations/workflows.js
- lib/services/logicManagement/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3263
> [AutoPR logic/resource-manager] Adding in description of available filter options

- lib/services/computerVision/lib/models/imageTag.js
- lib/services/computerVision/lib/models/index.d.ts
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3259
> [AutoPR cognitiveservices/data-plane/ComputerVision] ComputerVision add tag.hint

- runtime/ms-rest/Changelog.md
- runtime/ms-rest/index.d.ts
- runtime/ms-rest/lib/serialization.js
- runtime/ms-rest/package.json
- runtime/ms-rest/test/serializationTests.js
> x-nullable

- lib/services/storageManagement2/lib/models/endpoints.js
- lib/services/storageManagement2/lib/models/index.d.ts
- lib/services/storageManagement2/lib/models/storageAccount.js
- lib/services/storageManagement2/lib/models/storageAccountCreateParameters.js
- lib/services/storageManagement2/lib/operations/index.d.ts
- lib/services/storageManagement2/lib/operations/storageAccounts.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3289
> [AutoPR storage/resource-manager] [Storage] Support HDFS feature and web endpoint in Account properties 

- lib/services/storageManagement2/lib/models/endpoints.js
- lib/services/storageManagement2/lib/models/index.d.ts
- lib/services/storageManagement2/lib/models/storageAccount.js
- lib/services/storageManagement2/lib/models/storageAccountCreateParameters.js
- lib/services/storageManagement2/lib/operations/index.d.ts
- lib/services/storageManagement2/lib/operations/storageAccounts.js
- lib/services/storageManagement2/package-lock.json
- lib/services/storageManagement2/package.json
Resolves https://github.com/Azure/azure-sdk-for-node/issues/3067.
> Regenerate storage management SDK and bump version to 5.1.0-preview

- lib/services/containerRegistryManagement/lib/models/buildFilter.js
- lib/services/containerRegistryManagement/lib/models/index.d.ts
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3313
> [AutoPR containerregistry/resource-manager] [ACR] Fix list builds odata query

- lib/services/eventHubManagement/lib/models/armDisasterRecovery.js
- lib/services/eventHubManagement/lib/models/index.d.ts
- lib/services/eventHubManagement/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3315
> [AutoPR eventhub/resource-manager] Event Hubs : Added property pendingReplicationOperationsCount to GeoDR

- lib/services/eventHubManagement/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3294
> [AutoPR eventhub/resource-manager] Event Hubs 2018-01-01: renamed and added VirtualNetworkRules and IPFilterRules

- lib/services/serviceBusManagement2/lib/models/armDisasterRecovery.js
- lib/services/serviceBusManagement2/lib/models/migrationConfigProperties.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3330
> [AutoPR servicebus/resource-manager] ServiceBus: Removed space from pendingReplicationOperationsCount

- lib/services/batchaiManagement/lib/models/index.d.ts
- lib/services/batchaiManagement/lib/models/job.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3328
> [AutoPR batchai/resource-manager] Rename MPI to CustomMPI to match Batch AI service

- lib/services/batch/lib/models/cloudJob.js
- lib/services/batch/lib/models/cloudJobSchedule.js
- lib/services/batch/lib/models/cloudTask.js
- lib/services/batch/lib/models/index.d.ts
- lib/services/batch/lib/models/jobAddParameter.js
- lib/services/batch/lib/models/jobManagerTask.js
- lib/services/batch/lib/models/jobPreparationTask.js
- lib/services/batch/lib/models/jobReleaseTask.js
- lib/services/batch/lib/models/jobScheduleAddParameter.js
- lib/services/batch/lib/models/jobSchedulePatchParameter.js
- lib/services/batch/lib/models/jobScheduleUpdateParameter.js
- lib/services/batch/lib/models/jobSpecification.js
- lib/services/batch/lib/models/multiInstanceSettings.js
- lib/services/batch/lib/models/startTask.js
- lib/services/batch/lib/models/taskAddCollectionParameter.js
- lib/services/batch/lib/models/taskAddParameter.js
- lib/services/batch/lib/operations/index.d.ts
- lib/services/batch/lib/operations/job.js
- lib/services/batch/lib/operations/jobSchedule.js
- lib/services/batch/lib/operations/pool.js
- lib/services/batch/lib/operations/task.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3320
> [AutoPR batch/data-plane] Update documentation of possible errors and size limits for Batch

- lib/services/customVision/training/lib/models/exportModel.js
- lib/services/customVision/training/lib/models/index.d.ts
- lib/services/customVision/training/lib/models/iteration.js
- lib/services/customVision/training/lib/models/project.js
- lib/services/customVision/training/lib/models/projectSettings.js
- lib/services/customVision/training/lib/trainingAPIClient.d.ts
- lib/services/customVision/training/lib/trainingAPIClient.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3337
> [AutoPR cognitiveservices/data-plane/CustomVision/Training] Custom vision 2.1 updates

- lib/services/networkManagement2/lib/models/index.d.ts
- lib/services/networkManagement2/lib/models/vpnConnection.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3375
> [AutoPR network/resource-manager] Renaming ConnectionBandwidthInMbps to ConnectionBandwidth

- lib/services/customVision/training/lib/models/exportModel.js
- lib/services/customVision/training/lib/models/index.d.ts
- lib/services/customVision/training/lib/models/iteration.js
- lib/services/customVision/training/lib/models/project.js
- lib/services/customVision/training/lib/models/projectSettings.js
- lib/services/customVision/training/lib/trainingAPIClient.d.ts
- lib/services/customVision/training/lib/trainingAPIClient.js
- lib/services/customVision/training/package-lock.json
- lib/services/customVision/training/package.json
Created to accumulate context: cognitiveservices/data-plane/CustomVision/Training
> [AutoPR] cognitiveservices/data-plane/CustomVision/Training

- lib/services/computeManagement2/lib/operations/index.d.ts
- lib/services/computeManagement2/lib/operations/virtualMachineScaleSets.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3394
> [AutoPR compute/resource-manager] Update VMSS planned maintenance description to refer to best practices doc

- lib/services/networkManagement2/lib/operations/index.d.ts
- lib/services/networkManagement2/lib/operations/vpnConnections.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3366
> [AutoPR network/resource-manager] Port fixes from 04-01 (master) to 06-01

- lib/services/hdInsightManagement/lib/models/index.d.ts
- lib/services/hdInsightManagement/lib/models/storageAccount.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3376
> [AutoPR hdinsight/resource-manager] [HDInsight] Added support for ADLS type Gen 2

- lib/services/computeManagement2/lib/models/index.d.ts
- lib/services/computeManagement2/lib/models/virtualMachineScaleSet.js
- lib/services/computeManagement2/lib/models/virtualMachineScaleSetDataDisk.js
- lib/services/computeManagement2/lib/models/virtualMachineScaleSetOSDisk.js
- lib/services/computeManagement2/lib/models/virtualMachineScaleSetStorageProfile.js
- lib/services/computeManagement2/lib/models/virtualMachineScaleSetUpdate.js
- lib/services/computeManagement2/lib/models/virtualMachineScaleSetUpdateOSDisk.js
- lib/services/computeManagement2/lib/models/virtualMachineScaleSetUpdateStorageProfile.js
- lib/services/computeManagement2/lib/models/virtualMachineScaleSetUpdateVMProfile.js
- lib/services/computeManagement2/lib/models/virtualMachineScaleSetVM.js
- lib/services/computeManagement2/lib/models/virtualMachineScaleSetVMProfile.js
- lib/services/computeManagement2/lib/operations/index.d.ts
- lib/services/computeManagement2/lib/operations/virtualMachineScaleSets.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3406
> [AutoPR compute/resource-manager] Add missing ScaleSet properties

- lib/services/networkManagement2/lib/models/applicationGatewayAvailableSslOptions.js
- lib/services/networkManagement2/lib/models/applicationGatewaySslPolicy.js
- lib/services/networkManagement2/lib/models/applicationGatewaySslPredefinedPolicy.js
- lib/services/networkManagement2/lib/models/azureFirewallNetworkRule.js
- lib/services/networkManagement2/lib/models/packetCaptureQueryStatusResult.js
- lib/services/networkManagement2/lib/models/vpnClientConfiguration.js
- lib/services/networkManagement2/lib/networkManagementClient.d.ts
- lib/services/networkManagement2/lib/networkManagementClient.js
- lib/services/networkManagement2/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3529
> [AutoPR network/resource-manager] add package-2018-06 to Go SDK

- lib/services/storageManagement2/lib/models/index.d.ts
- lib/services/storageManagement2/lib/models/operation.js
- lib/services/storageManagement2/lib/models/operationDisplay.js
- lib/services/storageManagement2/lib/models/restriction.js
- lib/services/storageManagement2/lib/models/serviceSasParameters.js
- lib/services/storageManagement2/lib/operations/index.d.ts
- lib/services/storageManagement2/lib/operations/storageAccounts.js
- lib/services/storageManagement2/lib/storageManagementClient.d.ts
- lib/services/storageManagement2/lib/storageManagementClient.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3463
> [AutoPR storage/resource-manager] [Storage] Set the SignedResource as optional in ListServiceSAS

- lib/services/containerinstanceManagement/lib/operations/containerGroups.js
- lib/services/containerinstanceManagement/lib/operations/index.d.ts
- lib/services/containerinstanceManagement/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3556
> [AutoPR containerinstance/resource-manager] Add Contaienr Group Stop and Restart API

- lib/services/hdInsightManagement/lib/operations/applications.js
- lib/services/hdInsightManagement/lib/operations/index.d.ts
- lib/services/hdInsightManagement/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3565
> [AutoPR hdinsight/resource-manager] [HDInsight] Fixed PUT application parameter

- lib/services/networkManagement2/lib/models/applicationGatewayBackendHealthServer.js
- lib/services/networkManagement2/lib/models/frontendIPConfiguration.js
- lib/services/networkManagement2/lib/models/iPConfiguration.js
- lib/services/networkManagement2/lib/models/inboundNatRule.js
- lib/services/networkManagement2/lib/models/index.d.ts
- lib/services/networkManagement2/lib/models/networkInterfaceIPConfiguration.js
- lib/services/networkManagement2/lib/models/publicIPAddress.js
- lib/services/networkManagement2/lib/models/publicIPPrefix.js
- lib/services/networkManagement2/lib/operations/index.d.ts
- lib/services/networkManagement2/lib/operations/publicIPAddresses.js
- lib/services/networkManagement2/lib/operations/publicIPPrefixes.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3573
> [AutoPR network/resource-manager] Publicipprefixaugust

- lib/services/sqlManagement2/lib/models/databaseVulnerabilityAssessment.js
- lib/services/sqlManagement2/lib/models/index.d.ts
- lib/services/sqlManagement2/lib/operations/databaseVulnerabilityAssessments.js
- lib/services/sqlManagement2/lib/operations/index.d.ts
- lib/services/sqlManagement2/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3579
> [AutoPR sql/resource-manager] fix SQL VA command copy paste typo

- lib/services/monitorManagement/lib/models/autoscaleProfile.js
- lib/services/monitorManagement/lib/models/index.d.ts
- lib/services/monitorManagement/lib/models/recurrence.js
- lib/services/monitorManagement/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3586
> [AutoPR monitor/resource-manager] [Monitor] Fix issue #3585: revert previous commit since it is a brealing change

- lib/services/networkManagement2/lib/models/applicationGatewayAvailableSslOptions.js
- lib/services/networkManagement2/lib/models/applicationGatewaySslPolicy.js
- lib/services/networkManagement2/lib/models/applicationGatewaySslPredefinedPolicy.js
- lib/services/networkManagement2/lib/models/azureFirewallNetworkRule.js
- lib/services/networkManagement2/lib/models/packetCaptureQueryStatusResult.js
- lib/services/networkManagement2/lib/models/vpnClientConfiguration.js
- lib/services/networkManagement2/lib/networkManagementClient.d.ts
- lib/services/networkManagement2/lib/networkManagementClient.js
- lib/services/networkManagement2/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3597
> [AutoPR network/resource-manager] add x-ms-long-running-operation-options to query packet capture status

- lib/services/containerservicesManagement/lib/models/containerServiceLinuxProfile.js
- lib/services/containerservicesManagement/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3591
> [AutoPR containerservices/resource-manager] [AKS] regex bug fix for LinuxProfile.AdminUser

- lib/services/containerservicesManagement/lib/models/credentialResults.js
- lib/services/containerservicesManagement/lib/models/index.d.ts
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3606
> [AutoPR containerservices/resource-manager] [AKS]modify credentialResults keyName to kubeconfigs

- lib/services/containerservicesManagement/lib/models/credentialResult.js
- lib/services/containerservicesManagement/lib/models/index.d.ts
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3613
> [AutoPR containerservices/resource-manager] [AKS] fix CredentialResult value format

- lib/services/websiteManagement2/lib/models/csmPublishingProfileOptions.js
- lib/services/websiteManagement2/lib/models/index.d.ts
- lib/services/websiteManagement2/lib/operations/index.d.ts
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3589
> [AutoPR web/resource-manager] Include DRSecondary endpoint for GetPublishingProfileXml

- lib/services/logicManagement/lib/operations/workflowTriggers.js
- lib/services/logicManagement/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3616
> [AutoPR logic/resource-manager] Fix for extra / on the end of the triggers endpoint

- lib/services/sqlManagement2/lib/operations/index.d.ts
- lib/services/sqlManagement2/lib/operations/sensitivityLabels.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3627
> [AutoPR sql/resource-manager] [DO NOT MERGE]

- lib/services/batchManagement/lib/batchManagementClient.d.ts
- lib/services/batchManagement/lib/batchManagementClient.js
- lib/services/batchManagement/lib/models/batchAccount.js
- lib/services/batchManagement/lib/models/certificate.js
- lib/services/batchManagement/lib/models/certificateBaseProperties.js
- lib/services/batchManagement/lib/models/certificateCreateOrUpdateParameters.js
- lib/services/batchManagement/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3651
> [AutoPR batch/resource-manager] Adding suppressions for Microsoft.Batch RP API

- lib/services/computeManagement2/lib/computeManagementClient.d.ts
- lib/services/computeManagement2/lib/computeManagementClient.js
- lib/services/computeManagement2/lib/models/accessUri.js
- lib/services/computeManagement2/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3642
> [AutoPR compute/resource-manager] [Compute] add zone and rolling upgrade.

- lib/services/cdnManagement/LICENSE.txt
- lib/services/cdnManagement/lib/cdnManagementClient.d.ts
- lib/services/cdnManagement/lib/cdnManagementClient.js
- lib/services/cdnManagement/lib/models/cacheExpirationActionParameters.js
- lib/services/cdnManagement/lib/models/index.d.ts
- lib/services/cdnManagement/lib/models/profile.js
- lib/services/cdnManagement/lib/models/sku.js
- lib/services/cdnManagement/lib/models/supportedOptimizationTypesListResult.js
- lib/services/cdnManagement/lib/operations/index.d.ts
- lib/services/cdnManagement/lib/operations/profiles.js
- lib/services/cdnManagement/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3628
> [AutoPR cdn/resource-manager] adding standard_microsoft in pricing tier

- lib/services/networkManagement2/lib/models/applicationGatewayBackendHealthServer.js
- lib/services/networkManagement2/lib/models/frontendIPConfiguration.js
- lib/services/networkManagement2/lib/models/iPConfiguration.js
- lib/services/networkManagement2/lib/models/inboundNatRule.js
- lib/services/networkManagement2/lib/models/index.d.ts
- lib/services/networkManagement2/lib/models/networkInterfaceIPConfiguration.js
- lib/services/networkManagement2/lib/models/publicIPAddress.js
- lib/services/networkManagement2/lib/models/subnet.js
- lib/services/networkManagement2/lib/operations/index.d.ts
- lib/services/networkManagement2/lib/operations/subnets.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3714
> [AutoPR network/resource-manager] Added AddressPrefixes on Subnet properties

- lib/services/computeManagement2/lib/operations/index.d.ts
- lib/services/computeManagement2/lib/operations/virtualMachineSizes.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3722
> [AutoPR compute/resource-manager] RDBug 13056055 - Update description to deprecated. 

- lib/services/batchManagement/lib/batchManagementClient.d.ts
- lib/services/batchManagement/lib/batchManagementClient.js
- lib/services/batchManagement/lib/models/batchAccount.js
- lib/services/batchManagement/lib/models/certificate.js
- lib/services/batchManagement/lib/models/certificateBaseProperties.js
- lib/services/batchManagement/lib/models/certificateCreateOrUpdateParameters.js
- lib/services/batchManagement/package.json
Created to accumulate context: batch/resource-manager
> [AutoPR] batch/resource-manager

- lib/services/networkManagement2/lib/models/index.d.ts
- lib/services/networkManagement2/lib/models/outboundRule.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3728
> [AutoPR network/resource-manager] Changes to include required properties for outbound rule

- lib/services/iothub/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3733
> [AutoPR iothub/resource-manager] IoTHub conf py

- lib/services/visualstudioManagement/LICENSE.txt
- lib/services/visualstudioManagement/README.md
- lib/services/visualstudioManagement/lib/visualStudioResourceProviderClient.d.ts
- lib/services/visualstudioManagement/lib/visualStudioResourceProviderClient.js
- lib/services/visualstudioManagement/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3685
> [AutoPR visualstudio/resource-manager] Support for pipeline templates in microsoft.visualstudio RP

- lib/services/storagesyncManagement/lib/models/operationEntity.js
- lib/services/storagesyncManagement/lib/models/postRestoreRequest.js
- lib/services/storagesyncManagement/lib/models/preRestoreRequest.js
- lib/services/storagesyncManagement/lib/models/storageSyncError.js
- lib/services/storagesyncManagement/lib/models/workflowArray.js
- lib/services/storagesyncManagement/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3755
> [AutoPR storagesync/resource-manager] Change ApiVersion in examples. Change csharp output folder

- swagger_to_sdk_config.json
@latest didn't work out as I had hoped. We have to use real version numbers if we want to ensure that we get a specific version.
> Update swagger_to_sdk_config.json file

- lib/services/authorizationManagement/lib/models/index.d.ts
- lib/services/authorizationManagement/lib/models/providerOperationsMetadata.js
- lib/services/authorizationManagement/lib/models/resourceType.js
- lib/services/authorizationManagement/lib/models/roleAssignmentCreateParameters.js
- lib/services/authorizationManagement/lib/models/roleDefinition.js
- lib/services/authorizationManagement/lib/operations/index.d.ts
- lib/services/authorizationManagement/lib/operations/permissions.js
- lib/services/authorizationManagement/lib/operations/providerOperationsMetadataOperations.js
- lib/services/authorizationManagement/lib/operations/roleAssignments.js
- lib/services/authorizationManagement/lib/operations/roleDefinitions.js
- lib/services/authorizationManagement/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3737
> [AutoPR authorization/resource-manager] Grlin/Adding Principal Type to RA

- lib/services/eventgridManagement/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3765
> [AutoPR eventgrid/resource-manager] EventGrid management APIs: Swagger for new Preview API version

- lib/services/containerinstanceManagement/lib/models/containerGroup.js
- lib/services/containerinstanceManagement/lib/models/index.d.ts
- lib/services/containerinstanceManagement/lib/models/ipAddress.js
- lib/services/containerinstanceManagement/lib/operations/containerGroups.js
- lib/services/containerinstanceManagement/lib/operations/index.d.ts
- lib/services/containerinstanceManagement/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3823
> [AutoPR containerinstance/resource-manager] Container Instance: Add Private for Ip Address Enum

- lib/services/containerinstanceManagement/lib/models/containerGroup.js
- lib/services/containerinstanceManagement/lib/models/index.d.ts
- lib/services/containerinstanceManagement/lib/models/ipAddress.js
- lib/services/containerinstanceManagement/lib/operations/containerGroups.js
- lib/services/containerinstanceManagement/lib/operations/index.d.ts
- lib/services/containerinstanceManagement/package.json
Created to accumulate context: containerinstance/resource-manager
> [AutoPR] containerinstance/resource-manager

- lib/services/authorizationManagement/lib/models/index.d.ts
- lib/services/authorizationManagement/lib/models/roleAssignmentCreateParameters.js
- lib/services/authorizationManagement/lib/operations/index.d.ts
- lib/services/authorizationManagement/lib/operations/roleAssignments.js
- lib/services/authorizationManagement/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3852
> [AutoPR authorization/resource-manager] Grlin/updatingReqsforRA

- lib/services/networkManagement2/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3862
> [AutoPR network/resource-manager] Local september branch merge to master

- lib/services/monitorManagement/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3869
> [AutoPR monitor/resource-manager] Fix Go SDK generation

- lib/services/sqlManagement2/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3878
> [AutoPR sql/resource-manager] [DO NOT MERGE] Added list support to VA policies

- lib/services/automationManagement/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3899
> [AutoPR automation/resource-manager] Fix to version in examples and in runbook.json

- lib/services/networkManagement2/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3907
> [AutoPR network/resource-manager] Add 202 response code as expected for network profile deletion

- lib/services/logicManagement/lib/operations/integrationAccountSessions.js
- lib/services/logicManagement/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3868
> [AutoPR logic/resource-manager] Remove default response from Sessions

- lib/services/monitorManagement/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3883
> [AutoPR monitor/resource-manager] Add specifications for dynanic threshold GA api

- lib/services/sqlManagement2/lib/models/databaseSecurityAlertPolicy.js
- lib/services/sqlManagement2/lib/models/index.d.ts
- lib/services/sqlManagement2/lib/models/serverSecurityAlertPolicy.js
- lib/services/sqlManagement2/lib/operations/databaseThreatDetectionPolicies.js
- lib/services/sqlManagement2/lib/operations/index.d.ts
- lib/services/sqlManagement2/lib/operations/serverSecurityAlertPolicies.js
- lib/services/sqlManagement2/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3876
> [AutoPR sql/resource-manager] Add algorithm types to threat detection disabled alerts description

- lib/services/storagesyncManagement/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3927
> [AutoPR storagesync/resource-manager] StorageSync : Clone existing ApiVersion 2018-04-02 for creating a new version 2018-07-01

- lib/services/monitorManagement/lib/models/index.d.ts
- lib/services/monitorManagement/lib/models/metricTrigger.js
- lib/services/monitorManagement/lib/models/scaleRule.js
- lib/services/monitorManagement/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3921
> [AutoPR monitor/resource-manager] Add missing enum for aggregation type

- lib/services/datafactoryManagement/lib/models/activityPolicy.js
- lib/services/datafactoryManagement/lib/models/executionActivity.js
- lib/services/datafactoryManagement/lib/models/index.d.ts
- lib/services/datafactoryManagement/lib/operations/index.d.ts
- lib/services/datafactoryManagement/lib/operations/pipelineRuns.js
- lib/services/datafactoryManagement/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3917
> [AutoPR datafactory/resource-manager] [Datafactory] Add SecureInput property to Activity. Add recursive option to cancel API 

- lib/services/resourceManagement/lib/lock/managementLockClient.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3960
> [AutoPR resources/resource-manager] Fix typo, the provider should be Microsoft.Authorization

- lib/services/resourceManagement/package.json
I forgot to bump the version number of the recent azure-arm-resource PR I just merged.
> Update azure-arm-resource to 5.1.1

- lib/services/recoveryServicesBackupManagement/lib/models/azureIaaSVMJobExtendedInfo.js
- lib/services/recoveryServicesBackupManagement/lib/models/azureStorageJobExtendedInfo.js
- lib/services/recoveryServicesBackupManagement/lib/models/azureWorkloadContainerExtendedInfo.js
- lib/services/recoveryServicesBackupManagement/lib/models/azureWorkloadJobExtendedInfo.js
- lib/services/recoveryServicesBackupManagement/lib/models/azureWorkloadSQLRecoveryPointExtendedInfo.js
- lib/services/recoveryServicesBackupManagement/lib/models/backupEngineBase.js
- lib/services/recoveryServicesBackupManagement/lib/models/backupManagementUsage.js
- lib/services/recoveryServicesBackupManagement/lib/models/clientDiscoveryForProperties.js
- lib/services/recoveryServicesBackupManagement/lib/models/clientDiscoveryForServiceSpecification.js
- lib/services/recoveryServicesBackupManagement/lib/models/clientDiscoveryValueForSingleApi.js
- lib/services/recoveryServicesBackupManagement/lib/models/dailyRetentionFormat.js
- lib/services/recoveryServicesBackupManagement/lib/models/dailyRetentionSchedule.js
- lib/services/recoveryServicesBackupManagement/lib/models/distributedNodesInfo.js
- lib/services/recoveryServicesBackupManagement/lib/models/dpmJobExtendedInfo.js
- lib/services/recoveryServicesBackupManagement/lib/models/genericContainerExtendedInfo.js
- lib/services/recoveryServicesBackupManagement/lib/models/inquiryInfo.js
- lib/services/recoveryServicesBackupManagement/lib/models/inquiryValidation.js
- lib/services/recoveryServicesBackupManagement/lib/models/instantItemRecoveryTarget.js
- lib/services/recoveryServicesBackupManagement/lib/models/keyAndSecretDetails.js
- lib/services/recoveryServicesBackupManagement/lib/models/mabJobExtendedInfo.js
- lib/services/recoveryServicesBackupManagement/lib/models/monthlyRetentionSchedule.js
- lib/services/recoveryServicesBackupManagement/lib/models/operationStatus.js
- lib/services/recoveryServicesBackupManagement/lib/models/subProtectionPolicy.js
- lib/services/recoveryServicesBackupManagement/lib/models/validateOperationResponse.js
- lib/services/recoveryServicesBackupManagement/lib/models/validateOperationsResponse.js
- lib/services/recoveryServicesBackupManagement/lib/models/weeklyRetentionSchedule.js
- lib/services/recoveryServicesBackupManagement/lib/models/workloadInquiryDetails.js
- lib/services/recoveryServicesBackupManagement/lib/models/yearlyRetentionSchedule.js
- lib/services/recoveryServicesBackupManagement/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3975
> [AutoPR recoveryservicesbackup/resource-manager] Move Go SDK config for back to its own config file

- lib/services/automationManagement/lib/operations/index.d.ts
- lib/services/automationManagement/lib/operations/runbookDraftOperations.js
- lib/services/automationManagement/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3913
> [AutoPR automation/resource-manager] Quick fix to response type of runbookdraftcontent get

- lib/services/graphManagement/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3947
> [AutoPR graphrbac/data-plane] Rename Post to Grants

- lib/services/computeManagement2/lib/models/bootDiagnostics.js
- lib/services/computeManagement2/lib/models/bootDiagnosticsInstanceView.js
- lib/services/computeManagement2/lib/models/diagnosticsProfile.js
- lib/services/computeManagement2/lib/models/index.d.ts
- lib/services/computeManagement2/lib/models/virtualMachine.js
- lib/services/computeManagement2/lib/models/virtualMachineInstanceView.js
- lib/services/computeManagement2/lib/models/virtualMachineScaleSet.js
- lib/services/computeManagement2/lib/models/virtualMachineScaleSetUpdate.js
- lib/services/computeManagement2/lib/models/virtualMachineScaleSetUpdateVMProfile.js
- lib/services/computeManagement2/lib/models/virtualMachineScaleSetVM.js
- lib/services/computeManagement2/lib/models/virtualMachineScaleSetVMInstanceView.js
- lib/services/computeManagement2/lib/models/virtualMachineScaleSetVMProfile.js
- lib/services/computeManagement2/lib/models/virtualMachineUpdate.js
- lib/services/computeManagement2/lib/operations/index.d.ts
- lib/services/computeManagement2/lib/operations/virtualMachineScaleSetVMs.js
- lib/services/computeManagement2/lib/operations/virtualMachineScaleSets.js
- lib/services/computeManagement2/lib/operations/virtualMachines.js
- lib/services/computeManagement2/package.json
Created to accumulate context: compute/resource-manager
> [AutoPR] compute/resource-manager

- lib/services/trafficManagerManagement2/lib/models/endpoint.js
- lib/services/trafficManagerManagement2/lib/models/heatMapModel.js
- lib/services/trafficManagerManagement2/lib/models/index.d.ts
- lib/services/trafficManagerManagement2/lib/models/profile.js
- lib/services/trafficManagerManagement2/lib/models/proxyResource.js
- lib/services/trafficManagerManagement2/lib/models/resource.js
- lib/services/trafficManagerManagement2/lib/models/trackedResource.js
- lib/services/trafficManagerManagement2/lib/models/trafficManagerGeographicHierarchy.js
- lib/services/trafficManagerManagement2/lib/models/userMetricsModel.js
- lib/services/trafficManagerManagement2/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4003
> [AutoPR trafficmanager/resource-manager] Add UserMetricsModel to exception list for missing readOnly attribute.

- lib/services/websiteManagement2/lib/webSiteManagementClient.d.ts
- lib/services/websiteManagement2/lib/webSiteManagementClient.js
- lib/services/websiteManagement2/package.json
Created to accumulate context: web/resource-manager
> [AutoPR] web/resource-manager

- lib/services/deploymentmanagerManagement/lib/models/artifactSource.js
- lib/services/deploymentmanagerManagement/lib/models/artifactSourcePropertiesModel.js
- lib/services/deploymentmanagerManagement/lib/models/index.d.ts
- lib/services/deploymentmanagerManagement/lib/models/prePostStep.js
- lib/services/deploymentmanagerManagement/lib/models/rollout.js
- lib/services/deploymentmanagerManagement/lib/models/rolloutOperationInfo.js
- lib/services/deploymentmanagerManagement/lib/models/rolloutPropertiesModel.js
- lib/services/deploymentmanagerManagement/lib/models/rolloutRequest.js
- lib/services/deploymentmanagerManagement/lib/models/rolloutStep.js
- lib/services/deploymentmanagerManagement/lib/models/sasAuthentication.js
- lib/services/deploymentmanagerManagement/lib/models/serviceProperties.js
- lib/services/deploymentmanagerManagement/lib/models/serviceResource.js
- lib/services/deploymentmanagerManagement/lib/models/serviceTopologyProperties.js
- lib/services/deploymentmanagerManagement/lib/models/serviceTopologyResource.js
- lib/services/deploymentmanagerManagement/lib/models/serviceUnitProperties.js
- lib/services/deploymentmanagerManagement/lib/models/serviceUnitResource.js
- lib/services/deploymentmanagerManagement/lib/models/step.js
- lib/services/deploymentmanagerManagement/lib/models/stepOperationInfo.js
- lib/services/deploymentmanagerManagement/lib/models/stepResource.js
- lib/services/deploymentmanagerManagement/lib/operations/artifactSources.js
- lib/services/deploymentmanagerManagement/lib/operations/index.d.ts
- lib/services/deploymentmanagerManagement/lib/operations/rollouts.js
- lib/services/deploymentmanagerManagement/lib/operations/serviceTopologies.js
- lib/services/deploymentmanagerManagement/lib/operations/serviceUnits.js
- lib/services/deploymentmanagerManagement/lib/operations/services.js
- lib/services/deploymentmanagerManagement/lib/operations/steps.js
- lib/services/deploymentmanagerManagement/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4047
> [AutoPR deploymentmanager/resource-manager] DeploymentManager: Fix property name and enhance descriptions

- lib/services/deploymentmanagerManagement/lib/models/artifactSource.js
- lib/services/deploymentmanagerManagement/lib/models/artifactSourcePropertiesModel.js
- lib/services/deploymentmanagerManagement/lib/models/index.d.ts
- lib/services/deploymentmanagerManagement/lib/models/prePostStep.js
- lib/services/deploymentmanagerManagement/lib/models/rollout.js
- lib/services/deploymentmanagerManagement/lib/models/rolloutOperationInfo.js
- lib/services/deploymentmanagerManagement/lib/models/rolloutPropertiesModel.js
- lib/services/deploymentmanagerManagement/lib/models/rolloutRequest.js
- lib/services/deploymentmanagerManagement/lib/models/rolloutStep.js
- lib/services/deploymentmanagerManagement/lib/models/sasAuthentication.js
- lib/services/deploymentmanagerManagement/lib/models/serviceProperties.js
- lib/services/deploymentmanagerManagement/lib/models/serviceResource.js
- lib/services/deploymentmanagerManagement/lib/models/serviceTopologyProperties.js
- lib/services/deploymentmanagerManagement/lib/models/serviceTopologyResource.js
- lib/services/deploymentmanagerManagement/lib/models/serviceUnitProperties.js
- lib/services/deploymentmanagerManagement/lib/models/serviceUnitResource.js
- lib/services/deploymentmanagerManagement/lib/models/step.js
- lib/services/deploymentmanagerManagement/lib/models/stepOperationInfo.js
- lib/services/deploymentmanagerManagement/lib/models/stepResource.js
- lib/services/deploymentmanagerManagement/lib/operations/artifactSources.js
- lib/services/deploymentmanagerManagement/lib/operations/index.d.ts
- lib/services/deploymentmanagerManagement/lib/operations/rollouts.js
- lib/services/deploymentmanagerManagement/lib/operations/serviceTopologies.js
- lib/services/deploymentmanagerManagement/lib/operations/serviceUnits.js
- lib/services/deploymentmanagerManagement/lib/operations/services.js
- lib/services/deploymentmanagerManagement/lib/operations/steps.js
- lib/services/deploymentmanagerManagement/package.json
Created to accumulate context: deploymentmanager/resource-manager
> [AutoPR] deploymentmanager/resource-manager

- lib/services/cosmosdbManagement/lib/models/databaseAccount.js
- lib/services/cosmosdbManagement/lib/models/databaseAccountCreateUpdateParameters.js
- lib/services/cosmosdbManagement/lib/models/databaseAccountListConnectionStringsResult.js
- lib/services/cosmosdbManagement/lib/models/databaseAccountPatchParameters.js
- lib/services/cosmosdbManagement/lib/models/failoverPolicies.js
- lib/services/cosmosdbManagement/lib/models/index.d.ts
- lib/services/cosmosdbManagement/lib/models/metric.js
- lib/services/cosmosdbManagement/lib/models/metricDefinition.js
- lib/services/cosmosdbManagement/lib/models/operation.js
- lib/services/cosmosdbManagement/lib/models/percentileMetric.js
- lib/services/cosmosdbManagement/lib/models/usage.js
- lib/services/cosmosdbManagement/lib/operations/databaseAccounts.js
- lib/services/cosmosdbManagement/lib/operations/index.d.ts
- lib/services/cosmosdbManagement/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4041
> [AutoPR cosmos-db/resource-manager] Adding parameter enableMultipleWriteLocations in Cosmos DB

- lib/services/containerRegistryManagement/lib/models/sourceTrigger.js
- lib/services/containerRegistryManagement/lib/models/sourceTriggerUpdateParameters.js
- lib/services/containerRegistryManagement/lib/models/webhook.js
- lib/services/containerRegistryManagement/lib/models/webhookCreateParameters.js
- lib/services/containerRegistryManagement/lib/models/webhookUpdateParameters.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4070
> [AutoPR containerregistry/resource-manager] Move ACR C# specific config to C#

- lib/services/storagesyncManagement/lib/models/index.d.ts
- lib/services/storagesyncManagement/lib/models/registeredServer.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4109
> [AutoPR storagesync/resource-manager] Microsoft.StorageSync : Add Monitoring Configuration (Missing)

- lib/services/storagesyncManagement/lib/models/index.d.ts
- lib/services/storagesyncManagement/lib/models/registeredServer.js
- lib/services/storagesyncManagement/package.json
Created to accumulate context: storagesync/resource-manager
> [AutoPR] storagesync/resource-manager

- CONTRIBUTING.md
- README.md
added Microsoft open source code of conduct to `README.md` and `CONTRIBUTING.md`
> add Microsoft open source code of conduct 

- lib/services/graphManagement/lib/operations/index.d.ts
- lib/services/graphManagement/lib/operations/oAuth2.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4160
> [AutoPR graphrbac/data-plane] Fix operation named missed in #3947

- lib/services/computerVision/lib/models/index.d.ts
- lib/services/computerVision/lib/models/index.js
- lib/services/computerVision/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4158
> [AutoPR cognitiveservices/data-plane/ComputerVision] Split Ocr out into own Swagger file

- lib/services/computerVision/lib/models/index.d.ts
- lib/services/computerVision/lib/models/index.js
- lib/services/computerVision/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4156
> [AutoPR cognitiveservices/data-plane/ComputerVision] Rename examples to match generated names

- lib/services/containerRegistryManagement/lib/models/index.d.ts
- lib/services/containerRegistryManagement/lib/models/index.js
- lib/services/containerRegistryManagement/lib/models/registry.js
- lib/services/containerRegistryManagement/lib/models/registryUpdateParameters.js
- lib/services/containerRegistryManagement/lib/operations/index.d.ts
- lib/services/containerRegistryManagement/lib/operations/registries.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4220
> [AutoPR containerregistry/resource-manager] Revert the previous change: remove the identity properties

- lib/services/networkManagement2/lib/operations/expressRouteGateways.js
- lib/services/networkManagement2/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4103
> [AutoPR network/resource-manager] Remove error code from swagger

- lib/services/networkManagement2/lib/operations/expressRouteGateways.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4251
> [AutoPR network/resource-manager] Cherry pick NRP's changes from master to October branch

- lib/services/resourceManagement/lib/resource/operations/index.d.ts
- lib/services/resourceManagement/lib/resource/operations/resourceGroups.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4297
> [AutoPR resources/resource-manager] added to description of allowed characters for resource group name

- lib/services/eventgrid/lib/models/index.d.ts
- lib/services/eventgrid/lib/models/index.js
- lib/services/eventgrid/lib/models/mediaJobCanceledEventData.js
- lib/services/eventgrid/lib/models/mediaJobErroredEventData.js
- lib/services/eventgrid/lib/models/mediaJobFinishedEventData.js
- lib/services/eventgrid/lib/models/mediaJobOutput.js
- lib/services/eventgrid/lib/models/mediaJobOutputAsset.js
- lib/services/eventgrid/lib/models/mediaJobOutputCanceledEventData.js
- lib/services/eventgrid/lib/models/mediaJobOutputCancelingEventData.js
- lib/services/eventgrid/lib/models/mediaJobOutputErroredEventData.js
- lib/services/eventgrid/lib/models/mediaJobOutputFinishedEventData.js
- lib/services/eventgrid/lib/models/mediaJobOutputProcessingEventData.js
- lib/services/eventgrid/lib/models/mediaJobOutputScheduledEventData.js
- lib/services/eventgrid/lib/models/mediaJobOutputStateChangeEventData.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4260
> [AutoPR eventgrid/data-plane] Added missing discriminator property to MediaJobOutput

- lib/services/computeManagement2/lib/models/index.d.ts
- lib/services/computeManagement2/lib/models/virtualMachineExtension.js
- lib/services/computeManagement2/lib/models/virtualMachineExtensionUpdate.js
- lib/services/computeManagement2/lib/models/virtualMachineScaleSetExtension.js
- lib/services/computeManagement2/lib/operations/index.d.ts
- lib/services/computeManagement2/lib/operations/virtualMachineExtensions.js
- lib/services/computeManagement2/lib/operations/virtualMachineScaleSetExtensions.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4300
> [AutoPR compute/resource-manager] Adding provisionAfterExtensions property for extension sequencing

- lib/services/storagesyncManagement/lib/models/index.d.ts
- lib/services/storagesyncManagement/lib/models/triggerRolloverRequest.js
- lib/services/storagesyncManagement/lib/operations/index.d.ts
- lib/services/storagesyncManagement/lib/operations/registeredServers.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4308
> [AutoPR storagesync/resource-manager] StorageSync ResourceProvider : Bug Fix to change parameter name

- lib/services/automationManagement/lib/models/index.d.ts
- lib/services/automationManagement/lib/models/sourceControlSyncJob.js
- lib/services/automationManagement/lib/models/sourceControlSyncJobById.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4303
> [AutoPR automation/resource-manager] Reverting change: Replacing PartialSync for IncrementalSync for sync type and updating examples.

- lib/services/sqlManagement2/lib/models/backupLongTermRetentionPolicy.js
- lib/services/sqlManagement2/lib/models/index.d.ts
- lib/services/sqlManagement2/lib/operations/backupLongTermRetentionPolicies.js
- lib/services/sqlManagement2/lib/operations/index.d.ts
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4313
> [AutoPR sql/resource-manager] Fixed spelling mistake in SQL documentation

- lib/services/storagesyncManagement/lib/storageSyncManagementClient.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4317
> [AutoPR storagesync/resource-manager] Microsoft.StorageSync Change Host name from swagger spec

- lib/services/consumptionManagement/lib/operations/index.d.ts
- lib/services/consumptionManagement/lib/operations/marketplaces.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4327
> [AutoPR consumption/resource-manager] Introducing Marketplaces at Management Group Level

- lib/services/websiteManagement2/lib/operations/index.d.ts
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4295
> [AutoPR web/resource-manager] Fix network trace API REST format

- lib/services/graphManagement/lib/models/application.js
- lib/services/graphManagement/lib/models/index.d.ts
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4348
> [AutoPR graphrbac/data-plane] Fix #4346 - RequiredResourceAccess missing on GET

- lib/services/sqlManagement2/lib/models/databaseBlobAuditingPolicy.js
- lib/services/sqlManagement2/lib/models/extendedDatabaseBlobAuditingPolicy.js
- lib/services/sqlManagement2/lib/models/extendedServerBlobAuditingPolicy.js
- lib/services/sqlManagement2/lib/models/index.d.ts
- lib/services/sqlManagement2/lib/models/serverBlobAuditingPolicy.js
- lib/services/sqlManagement2/lib/operations/databaseBlobAuditingPolicies.js
- lib/services/sqlManagement2/lib/operations/extendedDatabaseBlobAuditingPolicies.js
- lib/services/sqlManagement2/lib/operations/extendedServerBlobAuditingPolicies.js
- lib/services/sqlManagement2/lib/operations/index.d.ts
- lib/services/sqlManagement2/lib/operations/serverBlobAuditingPolicies.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4340
> [AutoPR sql/resource-manager] Update BlobAuditing swaggers to support Azure Monitor audit target  

- lib/services/hdInsightManagement/lib/models/application.js
- lib/services/hdInsightManagement/lib/models/applicationGetHttpsEndpoint.js
- lib/services/hdInsightManagement/lib/models/applicationProperties.js
- lib/services/hdInsightManagement/lib/models/index.d.ts
- lib/services/hdInsightManagement/lib/operations/applications.js
- lib/services/hdInsightManagement/lib/operations/index.d.ts
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4364
> [AutoPR hdinsight/resource-manager] [HDInsight] Fixed non-existent extra parameter (bug)

- lib/services/websiteManagement2/lib/operations/index.d.ts
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4363
> [AutoPR web/resource-manager] Fix network trace API bugs (Retake)

- lib/services/containerRegistryManagement/lib/models/dockerBuildStep.js
- lib/services/containerRegistryManagement/lib/models/dockerBuildStepUpdateParameters.js
- lib/services/containerRegistryManagement/lib/models/encodedTaskStep.js
- lib/services/containerRegistryManagement/lib/models/encodedTaskStepUpdateParameters.js
- lib/services/containerRegistryManagement/lib/models/fileTaskStep.js
- lib/services/containerRegistryManagement/lib/models/fileTaskStepUpdateParameters.js
- lib/services/containerRegistryManagement/lib/models/index.d.ts
- lib/services/containerRegistryManagement/lib/models/task.js
- lib/services/containerRegistryManagement/lib/models/taskStepProperties.js
- lib/services/containerRegistryManagement/lib/models/taskStepUpdateParameters.js
- lib/services/containerRegistryManagement/lib/models/taskUpdateParameters.js
- lib/services/containerRegistryManagement/lib/operations/index.d.ts
- lib/services/containerRegistryManagement/lib/operations/tasks.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4389
> [AutoPR containerregistry/resource-manager] ACR: Add contextAccessToken to Task step

- lib/services/machinelearningservicesManagement/lib/models/aKS.js
- lib/services/machinelearningservicesManagement/lib/models/batchAI.js
- lib/services/machinelearningservicesManagement/lib/models/compute.js
- lib/services/machinelearningservicesManagement/lib/models/computeResource.js
- lib/services/machinelearningservicesManagement/lib/models/dataFactory.js
- lib/services/machinelearningservicesManagement/lib/models/hDInsight.js
- lib/services/machinelearningservicesManagement/lib/models/hDInsightProperties.js
- lib/services/machinelearningservicesManagement/lib/models/index.d.ts
- lib/services/machinelearningservicesManagement/lib/models/index.js
- lib/services/machinelearningservicesManagement/lib/models/workspace.js
- lib/services/machinelearningservicesManagement/lib/operations/index.d.ts
- lib/services/machinelearningservicesManagement/lib/operations/machineLearningCompute.js
- lib/services/machinelearningservicesManagement/lib/operations/workspaces.js
- lib/services/machinelearningservicesManagement/package.json
Resolves https://github.com/Azure/azure-sdk-for-node/issues/4022.
> Regenerate azure-arm-machinelearningservices

- lib/services/sqlManagement2/lib/models/databaseBlobAuditingPolicy.js
- lib/services/sqlManagement2/lib/models/extendedDatabaseBlobAuditingPolicy.js
- lib/services/sqlManagement2/lib/models/extendedServerBlobAuditingPolicy.js
- lib/services/sqlManagement2/lib/models/index.d.ts
- lib/services/sqlManagement2/lib/models/serverBlobAuditingPolicy.js
- lib/services/sqlManagement2/lib/operations/databaseBlobAuditingPolicies.js
- lib/services/sqlManagement2/lib/operations/extendedDatabaseBlobAuditingPolicies.js
- lib/services/sqlManagement2/lib/operations/extendedServerBlobAuditingPolicies.js
- lib/services/sqlManagement2/lib/operations/index.d.ts
- lib/services/sqlManagement2/lib/operations/serverBlobAuditingPolicies.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4403
> [AutoPR sql/resource-manager] Fix blob auditing documentation

- lib/services/sqlManagement2/lib/operations/databaseVulnerabilityAssessmentScans.js
- lib/services/sqlManagement2/lib/operations/index.d.ts
- lib/services/sqlManagement2/package.json
Created to accumulate context: sql/resource-manager
> [AutoPR] sql/resource-manager

- lib/services/networkManagement2/lib/models/index.d.ts
- lib/services/networkManagement2/lib/models/networkInterface.js
- lib/services/networkManagement2/lib/operations/index.d.ts
- lib/services/networkManagement2/lib/operations/networkInterfaces.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4443
> [AutoPR network/resource-manager] Make NIC VM ref readonly

- lib/services/networkManagement2/lib/models/index.d.ts
- lib/services/networkManagement2/lib/models/networkInterface.js
- lib/services/networkManagement2/lib/operations/index.d.ts
- lib/services/networkManagement2/lib/operations/networkInterfaces.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4444
> [AutoPR network/resource-manager] Make NIC VM readOnly

- lib/services/networkManagement2/lib/models/azureFirewallIPConfiguration.js
- lib/services/networkManagement2/lib/models/index.d.ts
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4447
> [AutoPR network/resource-manager] [AzureFirewall] Mark private IP address read-only

- lib/services/websiteManagement2/lib/models/deletedAppRestoreRequest.js
- lib/services/websiteManagement2/lib/models/deletedSite.js
- lib/services/websiteManagement2/lib/models/index.d.ts
- lib/services/websiteManagement2/lib/models/snapshotRestoreRequest.js
- lib/services/websiteManagement2/lib/operations/index.d.ts
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4448
> [AutoPR web/resource-manager] Add GeoRegion property to DeletedSite model

- lib/services/websiteManagement2/lib/models/deletedSite.js
- lib/services/websiteManagement2/lib/models/index.d.ts
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4453
> [AutoPR web/resource-manager] Add GeoRegion to DeletedSite Model

- lib/services/networkManagement2/lib/models/containerNetworkInterfaceConfiguration.js
- lib/services/networkManagement2/lib/models/index.d.ts
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4463
> [AutoPR network/resource-manager] Port fix from PR 4459 to 2018-10-01

- lib/services/logicManagement/lib/models/index.d.ts
- lib/services/logicManagement/lib/models/keyVaultReference.js
- lib/services/logicManagement/lib/models/resourceReference.js
- lib/services/logicManagement/lib/operations/index.d.ts
- lib/services/logicManagement/lib/operations/integrationAccounts.js
- lib/services/logicManagement/lib/operations/workflows.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4491
> [AutoPR logic/resource-manager] Microsoft.Logic - Don't make ResourceReference id readonly

- lib/services/websiteManagement2/lib/models/appServiceEnvironmentPatchResource.js
- lib/services/websiteManagement2/lib/models/index.d.ts
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4527
> [AutoPR web/resource-manager] typo: web/resource-manager/Microsoft.Web/AppServiceEnvironments

- lib/services/networkManagement2/lib/operations/index.d.ts
- lib/services/networkManagement2/lib/operations/virtualNetworks.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4547
> [AutoPR network/resource-manager] Ported fix from master branch

- lib/services/resourceManagement/lib/resource/models/index.d.ts
- lib/services/resourceManagement/lib/resource/models/tagDetails.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4600
> [AutoPR resources/resource-manager] Fix the ARM R2062 error for Microsoft.Resources

- lib/services/resourceManagement/lib/resource/models/index.d.ts
- lib/services/resourceManagement/lib/resource/models/tagDetails.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4618
> [AutoPR resources/resource-manager] Revert "Fix the ARM R2062 error for Microsoft.Resources"

- lib/services/computeManagement2/lib/models/diffDiskSettings.js
- lib/services/computeManagement2/lib/models/index.d.ts
- lib/services/computeManagement2/lib/models/oSDisk.js
- lib/services/computeManagement2/lib/models/storageProfile.js
- lib/services/computeManagement2/lib/models/virtualMachine.js
- lib/services/computeManagement2/lib/models/virtualMachineReimageParameters.js
- lib/services/computeManagement2/lib/models/virtualMachineScaleSet.js
- lib/services/computeManagement2/lib/models/virtualMachineScaleSetOSDisk.js
- lib/services/computeManagement2/lib/models/virtualMachineScaleSetStorageProfile.js
- lib/services/computeManagement2/lib/models/virtualMachineScaleSetVM.js
- lib/services/computeManagement2/lib/models/virtualMachineScaleSetVMProfile.js
- lib/services/computeManagement2/lib/models/virtualMachineUpdate.js
- lib/services/computeManagement2/lib/operations/index.d.ts
- lib/services/computeManagement2/lib/operations/virtualMachineScaleSetVMs.js
- lib/services/computeManagement2/lib/operations/virtualMachineScaleSets.js
- lib/services/computeManagement2/lib/operations/virtualMachines.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4644
> [AutoPR compute/resource-manager] updated Reimage API documentation in compute json for ephemeral os disks

- lib/services/datamigrationManagement/lib/models/connectToSourceSqlServerTaskOutputAgentJobLevel.js
- lib/services/datamigrationManagement/lib/models/connectToSourceSqlServerTaskOutputLoginLevel.js
- lib/services/datamigrationManagement/lib/models/index.d.ts
- lib/services/datamigrationManagement/lib/models/projectFile.js
- lib/services/datamigrationManagement/lib/models/projectFileProperties.js
- lib/services/datamigrationManagement/lib/models/resourceSkuCapabilities.js
- lib/services/datamigrationManagement/lib/models/selectedCertificateInput.js
- lib/services/datamigrationManagement/lib/operations/files.js
- lib/services/datamigrationManagement/lib/operations/index.d.ts
- lib/services/datamigrationManagement/lib/operations/tasks.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4681
> [AutoPR datamigration/resource-manager] typo: Microsoft.DataMigration

- lib/services/computeManagement2/lib/models/containerService.js
- lib/services/computeManagement2/lib/models/containerServiceAgentPoolProfile.js
- lib/services/computeManagement2/lib/models/containerServiceMasterProfile.js
- lib/services/computeManagement2/lib/models/index.d.ts
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4659
> [AutoPR compute/resource-manager] typo: Microsoft.ContainerService

- lib/services/graphManagement/lib/models/index.d.ts
- lib/services/graphManagement/lib/models/requiredResourceAccess.js
- lib/services/graphManagement/lib/operations/index.d.ts
- lib/services/graphManagement/lib/operations/oAuth2.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4693
> [AutoPR graphrbac/data-plane] typo: graphrbac

- lib/services/cosmosdbManagement/lib/operations/databaseAccounts.js
- lib/services/cosmosdbManagement/lib/operations/index.d.ts
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4665
> [AutoPR cosmos-db/resource-manager] typo: Microsoft.DocumentDB

- lib/services/policyinsightsManagement/lib/models/index.d.ts
- lib/services/policyinsightsManagement/lib/models/remediation.js
- lib/services/policyinsightsManagement/lib/models/remediationDeploymentSummary.js
- lib/services/policyinsightsManagement/lib/operations/index.d.ts
- lib/services/policyinsightsManagement/lib/operations/remediations.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4726
> [AutoPR policyinsights/resource-manager] typo: policyinsights/resource-manager/Microsoft.PolicyInsights

- lib/services/billingManagement/lib/models/index.d.ts
- lib/services/billingManagement/lib/models/invoice.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4632
> [AutoPR billing/resource-manager] typo: Microsoft.Billing

- lib/services/cognitiveServices/qnamaker/lib/models/index.d.ts
- lib/services/cognitiveServices/qnamaker/lib/models/updateMetadataDTO.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4653
> [AutoPR cognitiveservices/data-plane/QnAMaker] typo: cognitiveservices/data-plane/QnAMaker

- lib/services/eventgrid/lib/models/index.d.ts
- lib/services/eventgrid/lib/models/mediaLiveEventIncomingDataChunkDroppedEventData.js
- lib/services/eventgrid/lib/models/mediaLiveEventIngestHeartbeatEventData.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4687
> [AutoPR eventgrid/data-plane] typo: Microsoft.Media

- lib/services/datalake.Store/lib/filesystem/operations/fileSystem.js
- lib/services/datalake.Store/lib/filesystem/operations/index.d.ts
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4677
> [AutoPR datalake-store/data-plane] typo: Microsoft.DataLakeStore

- lib/services/resourceManagement/lib/link/operations/index.d.ts
- lib/services/resourceManagement/lib/link/operations/resourceLinks.js
- lib/services/resourceManagement/lib/resource/models/deploymentExtended.js
- lib/services/resourceManagement/lib/resource/models/deploymentPropertiesExtended.js
- lib/services/resourceManagement/lib/resource/models/deploymentValidateResult.js
- lib/services/resourceManagement/lib/resource/models/index.d.ts
- lib/services/resourceManagement/lib/resource/models/parametersLink.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4755
> [AutoPR resources/resource-manager] typo: resources/resource-manager/Microsoft.Resources

- lib/services/postgresqlManagement/lib/models/index.d.ts
- lib/services/postgresqlManagement/lib/models/operation.js
- lib/services/postgresqlManagement/lib/models/operationListResult.js
- lib/services/postgresqlManagement/lib/models/performanceTierProperties.js
- lib/services/postgresqlManagement/lib/models/serverForCreate.js
- lib/services/postgresqlManagement/lib/models/serverPropertiesForCreate.js
- lib/services/postgresqlManagement/lib/models/serverUpdateParameters.js
- lib/services/postgresqlManagement/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4727
> [AutoPR postgresql/resource-manager] typo: postgresql/resource-manager/Microsoft.DBforPostgreSQL

- lib/services/signalrManagement/lib/models/index.d.ts
- lib/services/signalrManagement/lib/models/resource.js
- lib/services/signalrManagement/lib/models/signalRUsage.js
- lib/services/signalrManagement/lib/models/signalRUsageName.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4781
> [AutoPR signalr/resource-manager] typo: signalr/resource-manager/Microsoft.SignalRService

- lib/services/storagesyncManagement/lib/operations/index.d.ts
- lib/services/storagesyncManagement/lib/operations/serverEndpoints.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4787
> [AutoPR storagesync/resource-manager] typo: storagesync/resource-manager/Microsoft.StorageSync

- lib/services/securityManagement/lib/models/externalSecuritySolution.js
- lib/services/securityManagement/lib/models/index.d.ts
- lib/services/securityManagement/lib/operations/alerts.js
- lib/services/securityManagement/lib/operations/index.d.ts
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4763
> [AutoPR security/resource-manager] typo: security/resource-manager/Microsoft.Security

- lib/services/applicationinsights/lib/models/aPIKeyRequest.js
- lib/services/applicationinsights/lib/models/applicationInsightsComponentAPIKey.js
- lib/services/applicationinsights/lib/models/applicationInsightsComponentExportConfiguration.js
- lib/services/applicationinsights/lib/models/applicationInsightsComponentListResult.js
- lib/services/applicationinsights/lib/models/applicationInsightsComponentProactiveDetectionConfiguration.js
- lib/services/applicationinsights/lib/models/applicationInsightsComponentProactiveDetectionConfigurationRuleDefinitions.js
- lib/services/applicationinsights/lib/models/errorResponse.js
- lib/services/applicationinsights/lib/models/index.d.ts
- lib/services/applicationinsights/lib/models/workItemCreateConfiguration.js
- lib/services/applicationinsights/lib/operations/index.d.ts
- lib/services/applicationinsights/lib/operations/proactiveDetectionConfigurations.js
- lib/services/applicationinsights/lib/operations/webTests.js
- lib/services/applicationinsights/lib/operations/workItemConfigurations.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4713
> [AutoPR applicationinsights/resource-manager] chore: Rename microsoft.insights to Microsoft.Insights

- lib/services/serviceFabricMeshManagement/lib/models/containerCodePackageProperties.js
- lib/services/serviceFabricMeshManagement/lib/models/httpHostConfig.js
- lib/services/serviceFabricMeshManagement/lib/models/index.d.ts
- lib/services/serviceFabricMeshManagement/lib/models/secretValueResourceDescriptionList.js
- lib/services/serviceFabricMeshManagement/lib/operations/index.d.ts
- lib/services/serviceFabricMeshManagement/lib/operations/secretValueOperations.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4779
> [AutoPR servicefabricmesh/resource-manager] typo: servicefabricmesh/resource-manager/Microsoft.ServiceFabricMesh

- .azure-pipelines/client.yml
This reverts commit 9a6f2f0b2ed09d87203e0e185465f15303cbc08c.
> Add ComponentGovernance

- lib/services/timeseriesinsightsManagement/lib/models/environmentResource.js
- lib/services/timeseriesinsightsManagement/lib/models/environmentStateDetails.js
- lib/services/timeseriesinsightsManagement/lib/models/environmentStatus.js
- lib/services/timeseriesinsightsManagement/lib/models/index.d.ts
- lib/services/timeseriesinsightsManagement/lib/models/ingressEnvironmentStatus.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4810
> [AutoPR timeseriesinsights/resource-manager] typo: timeseriesinsights/resource-manager/Microsoft.TimeSeriesInsights

- lib/services/logicManagement/lib/models/agreementContent.js
- lib/services/logicManagement/lib/models/edifactAgreementContent.js
- lib/services/logicManagement/lib/models/edifactOneWayAgreement.js
- lib/services/logicManagement/lib/models/edifactProtocolSettings.js
- lib/services/logicManagement/lib/models/edifactValidationOverride.js
- lib/services/logicManagement/lib/models/edifactValidationSettings.js
- lib/services/logicManagement/lib/models/index.d.ts
- lib/services/logicManagement/lib/models/integrationAccountAgreement.js
- lib/services/logicManagement/lib/models/x12AgreementContent.js
- lib/services/logicManagement/lib/models/x12OneWayAgreement.js
- lib/services/logicManagement/lib/models/x12ProtocolSettings.js
- lib/services/logicManagement/lib/models/x12ValidationOverride.js
- lib/services/logicManagement/lib/models/x12ValidationSettings.js
- lib/services/logicManagement/lib/operations/index.d.ts
- lib/services/logicManagement/lib/operations/integrationAccountAgreements.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4769
> [AutoPR logic/resource-manager] Bugfix for swagger/sdk not matching the underlying service API

- lib/services/resourceHealthManagement/lib/models/availabilityStatus.js
- lib/services/resourceHealthManagement/lib/models/availabilityStatusProperties.js
- lib/services/resourceHealthManagement/lib/models/operation.js
- lib/services/resourceHealthManagement/lib/models/operationListResult.js
- lib/services/resourceHealthManagement/lib/models/serviceImpactingEvent.js
- lib/services/resourceHealthManagement/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4830
> [AutoPR resourcehealth/resource-manager] typo: resourcehealth/resource-manager/Microsoft.ResourceHealth

- lib/services/serviceFabric/lib/models/backupInfo.js
- lib/services/serviceFabric/lib/models/backupProgressInfo.js
- lib/services/serviceFabric/lib/models/chaos.js
- lib/services/serviceFabric/lib/models/chaosParameters.js
- lib/services/serviceFabric/lib/models/chaosParametersDictionaryItem.js
- lib/services/serviceFabric/lib/models/chaosTargetFilter.js
- lib/services/serviceFabric/lib/models/containerCodePackageProperties.js
- lib/services/serviceFabric/lib/models/epoch.js
- lib/services/serviceFabric/lib/models/fabricError.js
- lib/services/serviceFabric/lib/models/fabricErrorError.js
- lib/services/serviceFabric/lib/models/httpHostConfig.js
- lib/services/serviceFabric/lib/models/index.d.ts
- lib/services/serviceFabric/lib/models/partitionBackupConfigurationInfo.js
- lib/services/serviceFabric/lib/models/partitionBackupEntity.js
- lib/services/serviceFabric/lib/models/restoreProgressInfo.js
- lib/services/serviceFabric/lib/models/startedChaosEvent.js
- lib/services/serviceFabric/lib/models/statefulServicePartitionInfo.js
- lib/services/serviceFabric/lib/operations/index.d.ts
- lib/services/serviceFabric/lib/operations/meshSecretValue.js
- lib/services/serviceFabric/lib/serviceFabricClient.d.ts
- lib/services/serviceFabric/lib/serviceFabricClient.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4834
> [AutoPR servicefabric/data-plane] typo: servicefabric/data-plane/Microsoft.ServiceFabric

- .azure-pipelines/client.yml
- lib/services/keyVault/package.json
- Version was accidentally incremented in https://github.com/Azure/azure-sdk-for-node/commit/a0443627390d6bdee9450bba37294ea69f394c9e#diff-34ec7e8370f59c8b845594c62c3e960e
> Change keyVault version to 3.0.4

- lib/services/containerRegistryManagement/lib/models/dockerBuildRequest.js
- lib/services/containerRegistryManagement/lib/models/encodedTaskRunRequest.js
- lib/services/containerRegistryManagement/lib/models/fileTaskRunRequest.js
- lib/services/containerRegistryManagement/lib/models/iPRule.js
- lib/services/containerRegistryManagement/lib/models/index.d.ts
- lib/services/containerRegistryManagement/lib/models/index.js
- lib/services/containerRegistryManagement/lib/models/networkRuleSet.js
- lib/services/containerRegistryManagement/lib/models/registry.js
- lib/services/containerRegistryManagement/lib/models/registryUpdateParameters.js
- lib/services/containerRegistryManagement/lib/models/sourceProperties.js
- lib/services/containerRegistryManagement/lib/models/sourceTrigger.js
- lib/services/containerRegistryManagement/lib/models/sourceTriggerUpdateParameters.js
- lib/services/containerRegistryManagement/lib/models/sourceUpdateParameters.js
- lib/services/containerRegistryManagement/lib/models/virtualNetworkRule.js
- lib/services/containerRegistryManagement/lib/operations/index.d.ts
- lib/services/containerRegistryManagement/lib/operations/registries.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4895
> [AutoPR containerregistry/resource-manager] [ACR] Add IP rules

- lib/services/trafficManagerManagement2/lib/models/index.d.ts
- lib/services/trafficManagerManagement2/lib/models/resource.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4812
> [AutoPR trafficmanager/resource-manager] typo: trafficmanager/resource-manager/Microsoft.Network

- lib/services/cognitiveServicesManagement/lib/models/checkSkuAvailabilityParameter.js
- lib/services/cognitiveServicesManagement/lib/models/checkSkuAvailabilityResult.js
- lib/services/cognitiveServicesManagement/lib/models/cognitiveServicesAccount.js
- lib/services/cognitiveServicesManagement/lib/models/cognitiveServicesAccountCreateParameters.js
- lib/services/cognitiveServicesManagement/lib/models/cognitiveServicesAccountUpdateParameters.js
- lib/services/cognitiveServicesManagement/lib/models/cognitiveServicesResourceAndSku.js
- lib/services/cognitiveServicesManagement/lib/models/index.d.ts
- lib/services/cognitiveServicesManagement/lib/models/sku.js
- lib/services/cognitiveServicesManagement/lib/operations/accounts.js
- lib/services/cognitiveServicesManagement/lib/operations/checkSkuAvailability.js
- lib/services/cognitiveServicesManagement/lib/operations/index.d.ts
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4913
> [AutoPR cognitiveservices/resource-manager] Change Kind and SKU name to string (from enum).

- lib/services/containerservicesManagement/lib/models/containerService.js
- lib/services/containerservicesManagement/lib/models/containerServiceAgentPoolProfile.js
- lib/services/containerservicesManagement/lib/models/containerServiceMasterProfile.js
- lib/services/containerservicesManagement/lib/models/index.d.ts
- lib/services/containerservicesManagement/lib/models/managedCluster.js
- lib/services/containerservicesManagement/lib/models/managedClusterAgentPoolProfile.js
- lib/services/containerservicesManagement/lib/models/openShiftRouterProfile.js
- lib/services/containerservicesManagement/lib/operations/containerServices.js
- lib/services/containerservicesManagement/lib/operations/index.d.ts
- lib/services/containerservicesManagement/lib/operations/managedClusters.js
- lib/services/containerservicesManagement/lib/operations/openShiftManagedClusters.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4896
> [AutoPR containerservices/resource-manager] [DO NOT MERGE] [AKS] add C# config to readme.md

- lib/services/labservicesManagement/lib/models/index.d.ts
- lib/services/labservicesManagement/lib/models/listEnvironmentsResponse.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4926
> [AutoPR labservices/resource-manager] typo: labservices/resource-manager/Microsoft.LabServices

- lib/services/batch/lib/models/computeNode.js
- lib/services/batch/lib/models/index.d.ts
- lib/services/batch/lib/models/virtualMachineConfiguration.js
- lib/services/batch/lib/operations/index.d.ts
- lib/services/batch/lib/operations/job.js
- lib/services/batch/lib/operations/jobSchedule.js
- lib/services/batch/lib/operations/pool.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4918
> [AutoPR batch/data-plane] typo: batch/data-plane/Microsoft.Batch

- lib/services/websiteManagement2/lib/models/analysisData.js
- lib/services/websiteManagement2/lib/models/certificate.js
- lib/services/websiteManagement2/lib/models/certificatePatchResource.js
- lib/services/websiteManagement2/lib/models/csmUsageQuota.js
- lib/services/websiteManagement2/lib/models/customHostnameAnalysisResult.js
- lib/services/websiteManagement2/lib/models/dataSource.js
- lib/services/websiteManagement2/lib/models/deployment.js
- lib/services/websiteManagement2/lib/models/detectorAbnormalTimePeriod.js
- lib/services/websiteManagement2/lib/models/diagnosticDetectorResponse.js
- lib/services/websiteManagement2/lib/models/index.d.ts
- lib/services/websiteManagement2/lib/models/processThreadInfo.js
- lib/services/websiteManagement2/lib/models/recommendation.js
- lib/services/websiteManagement2/lib/models/resourceNameAvailability.js
- lib/services/websiteManagement2/lib/models/responseMetaData.js
- lib/services/websiteManagement2/lib/models/site.js
- lib/services/websiteManagement2/lib/models/siteConfig.js
- lib/services/websiteManagement2/lib/models/siteConfigResource.js
- lib/services/websiteManagement2/lib/models/sitePatchResource.js
- lib/services/websiteManagement2/lib/models/validateRequest.js
- lib/services/websiteManagement2/lib/operations/appServicePlans.js
- lib/services/websiteManagement2/lib/operations/index.d.ts
- lib/services/websiteManagement2/lib/operations/recommendations.js
- lib/services/websiteManagement2/lib/webSiteManagementClient.d.ts
- lib/services/websiteManagement2/lib/webSiteManagementClient.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4919
> [AutoPR web/resource-manager] typo: web/resource-manager/Microsoft.Web

- lib/services/containerservicesManagement/lib/models/containerService.js
- lib/services/containerservicesManagement/lib/models/containerServiceAgentPoolProfile.js
- lib/services/containerservicesManagement/lib/models/containerServiceMasterProfile.js
- lib/services/containerservicesManagement/lib/models/index.d.ts
- lib/services/containerservicesManagement/lib/models/managedCluster.js
- lib/services/containerservicesManagement/lib/models/managedClusterAgentPoolProfile.js
- lib/services/containerservicesManagement/lib/models/openShiftRouterProfile.js
- lib/services/containerservicesManagement/lib/operations/containerServices.js
- lib/services/containerservicesManagement/lib/operations/index.d.ts
- lib/services/containerservicesManagement/lib/operations/managedClusters.js
- lib/services/containerservicesManagement/lib/operations/openShiftManagedClusters.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4917
> [AutoPR containerservices/resource-manager] [AKS] mark ACS endpoints as deprecated

- lib/services/networkManagement2/lib/operations/applicationSecurityGroups.js
- lib/services/networkManagement2/lib/operations/index.d.ts
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4951
> [AutoPR network/resource-manager] Exposing PATCH for Application Security Group (ASG)

- lib/services/securityManagement/LICENSE.txt
- lib/services/securityManagement/lib/models/dataExportSetting.js
- lib/services/securityManagement/lib/models/index.d.ts
- lib/services/securityManagement/lib/models/index.js
- lib/services/securityManagement/lib/models/settingResource.js
- lib/services/securityManagement/lib/models/settingsList.js
- lib/services/securityManagement/lib/operations/index.d.ts
- lib/services/securityManagement/lib/operations/settings.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4969
> [AutoPR security/resource-manager] Settings API - changed the kind to work with .net nuget

- lib/services/containerservicesManagement/LICENSE.txt
- lib/services/containerservicesManagement/lib/models/credentialResults.js
- lib/services/containerservicesManagement/lib/models/index.d.ts
- lib/services/containerservicesManagement/lib/operations/index.d.ts
- lib/services/containerservicesManagement/lib/operations/managedClusters.js
- lib/services/containerservicesManagement/lib/operations/openShiftManagedClusters.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4980
> [AutoPR containerservices/resource-manager] [AKS] add missing description fields

- lib/services/apimanagement/LICENSE.txt
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5000
> [AutoPR apimanagement/resource-manager] OpenAPIv3 support documented

- lib/services/computeManagement2/LICENSE.txt
- lib/services/computeManagement2/lib/models/index.d.ts
- lib/services/computeManagement2/lib/models/oSProfile.js
- lib/services/computeManagement2/lib/models/virtualMachine.js
- lib/services/computeManagement2/lib/models/virtualMachineScaleSetVM.js
- lib/services/computeManagement2/lib/models/virtualMachineUpdate.js
- lib/services/computeManagement2/lib/operations/index.d.ts
- lib/services/computeManagement2/lib/operations/virtualMachineScaleSetVMs.js
- lib/services/computeManagement2/lib/operations/virtualMachines.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4998
> [AutoPR compute/resource-manager] Update ComputerName definition for OsProfile

- lib/services/serviceBusManagement2/LICENSE.txt
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4989
> [AutoPR servicebus/resource-manager] Updated as per review comments from ARM Team for Eventhub swagger

- lib/services/logicManagement/lib/models/aS2AgreementContent.js
- lib/services/logicManagement/lib/models/aS2ErrorSettings.js
- lib/services/logicManagement/lib/models/aS2MdnSettings.js
- lib/services/logicManagement/lib/models/aS2OneWayAgreement.js
- lib/services/logicManagement/lib/models/aS2ProtocolSettings.js
- lib/services/logicManagement/lib/models/aS2SecuritySettings.js
- lib/services/logicManagement/lib/models/agreementContent.js
- lib/services/logicManagement/lib/models/index.d.ts
- lib/services/logicManagement/lib/models/integrationAccountAgreement.js
- lib/services/logicManagement/lib/operations/index.d.ts
- lib/services/logicManagement/lib/operations/integrationAccountAgreements.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5016
> [AutoPR logic/resource-manager] [LogicApps] Fix more acronyms that don't match API

- lib/services/logicManagement/lib/models/aS2AgreementContent.js
- lib/services/logicManagement/lib/models/aS2ErrorSettings.js
- lib/services/logicManagement/lib/models/aS2MdnSettings.js
- lib/services/logicManagement/lib/models/aS2OneWayAgreement.js
- lib/services/logicManagement/lib/models/aS2ProtocolSettings.js
- lib/services/logicManagement/lib/models/aS2SecuritySettings.js
- lib/services/logicManagement/lib/models/agreementContent.js
- lib/services/logicManagement/lib/models/index.d.ts
- lib/services/logicManagement/lib/models/integrationAccountAgreement.js
- lib/services/logicManagement/lib/operations/index.d.ts
- lib/services/logicManagement/lib/operations/integrationAccountAgreements.js
- lib/services/logicManagement/package.json
Created to accumulate context: logic/resource-manager
> [AutoPR] logic/resource-manager

- runtime/ms-rest-azure/.vscode/launch.json
- runtime/ms-rest-azure/lib/credentials/msiVmTokenCredentials.js
- runtime/ms-rest-azure/package.json
- runtime/ms-rest-azure/test/msiAppServiceTokenCredentialTests.js
- runtime/ms-rest-azure/test/msiVmTokenCredentialTests.js
Fixes https://github.com/Azure/azure-sdk-for-node/issues/2836
> Add support for custom MSI endpoint

- lib/services/datafactoryManagement/lib/models/index.d.ts
- lib/services/datafactoryManagement/lib/models/index.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5060
> [AutoPR datafactory/resource-manager] Remove webhook activity

- lib/services/datafactoryManagement/lib/models/index.d.ts
- lib/services/datafactoryManagement/lib/models/index.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5061
> [AutoPR datafactory/resource-manager] Revert DataFactory Validation Activity

- lib/services/iothub/LICENSE.txt
- lib/services/iothub/lib/models/index.d.ts
- lib/services/iothub/lib/models/routingStorageContainerProperties.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5069
> [AutoPR iothub/resource-manager] Adding JSON encoding type to storage endpoint

- lib/services/serviceBusManagement2/LICENSE.txt
- lib/services/serviceBusManagement2/lib/models/armDisasterRecovery.js
- lib/services/serviceBusManagement2/lib/models/checkNameAvailability.js
- lib/services/serviceBusManagement2/lib/models/errorResponse.js
- lib/services/serviceBusManagement2/lib/models/index.d.ts
- lib/services/serviceBusManagement2/lib/models/regenerateAccessKeyParameters.js
- lib/services/serviceBusManagement2/lib/models/sBNamespace.js
- lib/services/serviceBusManagement2/lib/models/sBNamespaceUpdateParameters.js
- lib/services/serviceBusManagement2/lib/models/sBTopic.js
- lib/services/serviceBusManagement2/lib/operations/disasterRecoveryConfigs.js
- lib/services/serviceBusManagement2/lib/operations/index.d.ts
- lib/services/serviceBusManagement2/lib/operations/migrationConfigs.js
- lib/services/serviceBusManagement2/lib/operations/namespaces.js
- lib/services/serviceBusManagement2/lib/operations/queues.js
- lib/services/serviceBusManagement2/lib/operations/topics.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4765
> [AutoPR servicebus/resource-manager] typo: servicebus/resource-manager/Microsoft.ServiceBus

- lib/services/securityManagement/lib/operations/index.d.ts
- lib/services/securityManagement/lib/operations/workspaceSettings.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5071
> [AutoPR security/resource-manager] Add description to empty result in Workspace Settings Get

- lib/services/recoveryServicesBackupManagement/lib/models/azureIaaSVMJobTaskDetails.js
- lib/services/recoveryServicesBackupManagement/lib/models/azureVmWorkloadItem.js
- lib/services/recoveryServicesBackupManagement/lib/models/azureVmWorkloadProtectableItem.js
- lib/services/recoveryServicesBackupManagement/lib/models/azureWorkloadRecoveryPoint.js
- lib/services/recoveryServicesBackupManagement/lib/models/azureWorkloadSAPHanaRecoveryPoint.js
- lib/services/recoveryServicesBackupManagement/lib/models/azureWorkloadSQLRecoveryPoint.js
- lib/services/recoveryServicesBackupManagement/lib/models/backupEngineBase.js
- lib/services/recoveryServicesBackupManagement/lib/models/backupEngineBaseResource.js
- lib/services/recoveryServicesBackupManagement/lib/models/backupEngineExtendedInfo.js
- lib/services/recoveryServicesBackupManagement/lib/models/dPMProtectedItem.js
- lib/services/recoveryServicesBackupManagement/lib/models/index.d.ts
- lib/services/recoveryServicesBackupManagement/lib/models/keyAndSecretDetails.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5063
> [AutoPR recoveryservicesbackup/resource-manager] typo: recoveryservicesbackup/resource-manager/Microsoft.RecoveryServices

- lib/services/resourceManagement/LICENSE.txt
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4971
> [AutoPR resources/resource-manager] Adding ResourceGroup example

- lib/services/cognitiveServicesFace/lib/models/findSimilarRequest.js
- lib/services/cognitiveServicesFace/lib/models/index.d.ts
- lib/services/cognitiveServicesFace/lib/operations/face.js
- lib/services/cognitiveServicesFace/lib/operations/index.d.ts
- lib/services/cognitiveServicesFace/lib/operations/snapshotOperations.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5094
> [AutoPR cognitiveservices/data-plane/Face] [Cogs Face] Refine the documentation for Face API's new Snapshot features. 

- lib/services/containerservicesManagement/lib/models/index.d.ts
- lib/services/containerservicesManagement/lib/models/managedCluster.js
- lib/services/containerservicesManagement/lib/operations/index.d.ts
- lib/services/containerservicesManagement/lib/operations/managedClusters.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5101
> [AutoPR containerservice/resource-manager] [AKS] add apiServerAuthorizedIPRanges property

- lib/services/networkManagement2/lib/models/azureFirewallNatRule.js
- lib/services/networkManagement2/lib/models/index.d.ts
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5112
> [AutoPR network/resource-manager] updated the destination address description to also include service tags

- lib/services/resourceHealthManagement/LICENSE.txt
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5116
> [AutoPR resourcehealth/resource-manager] Resourcehealth events response

- lib/services/eventHubManagement/LICENSE.txt
- lib/services/eventHubManagement/lib/models/captureDescription.js
- lib/services/eventHubManagement/lib/models/eventhub.js
- lib/services/eventHubManagement/lib/models/index.d.ts
- lib/services/eventHubManagement/lib/operations/eventHubs.js
- lib/services/eventHubManagement/lib/operations/index.d.ts
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5105
> [AutoPR eventhub/resource-manager] Eventhub: Added skipEmptyArchives to Eventhub CaptureDescription

- lib/services/computeManagement2/LICENSE.txt
- lib/services/computeManagement2/lib/models/disk.js
- lib/services/computeManagement2/lib/models/index.d.ts
- lib/services/computeManagement2/lib/models/oSProfile.js
- lib/services/computeManagement2/lib/models/virtualMachine.js
- lib/services/computeManagement2/lib/models/virtualMachineScaleSetVM.js
- lib/services/computeManagement2/lib/models/virtualMachineUpdate.js
- lib/services/computeManagement2/lib/operations/disks.js
- lib/services/computeManagement2/lib/operations/index.d.ts
- lib/services/computeManagement2/lib/operations/virtualMachineScaleSetVMs.js
- lib/services/computeManagement2/lib/operations/virtualMachines.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4866
> [AutoPR compute/resource-manager] Update compute.json to add ProtectFromScaleIn property to VMScaleSetVM properties

- runtime/ms-rest/.scripts/postinstall.js
- runtime/ms-rest/package.json
> Add script to print package deprecation message

- lib/services/computeManagement2/lib/models/index.d.ts
- lib/services/computeManagement2/lib/models/vaultCertificate.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5159
> [AutoPR compute/resource-manager] fixes for reference documentation

- lib/services/authorizationManagement/LICENSE.txt
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5154
> [AutoPR authorization/resource-manager] Removed "x-ms-pageable" from the elevateAccess API

- lib/services/policyinsightsManagement/lib/models/expressionEvaluationDetails.js
- lib/services/policyinsightsManagement/lib/models/index.d.ts
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5168
> [AutoPR policyinsights/resource-manager] typo: aliase -> alias

- lib/services/operationalInsightsManagement/LICENSE.txt
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5182
> [AutoPR operationalinsights/resource-manager] Add gateways API

- lib/services/postgresqlManagement/LICENSE.txt
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5203
> [AutoPR postgresql/resource-manager] Add server creation parameters to Postgres ResourceProvider for SDK

- .azure-pipelines/client.yml
- .docsettings.yml
> Adding .docsettings file. Adding Readme analysis to CI.

- lib/services/luis/authoring/LICENSE.txt
- lib/services/luis/authoring/lib/operations/index.d.ts
- lib/services/luis/authoring/lib/operations/model.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5216
> [AutoPR cognitiveservices/data-plane/LUIS/Authoring] [Cogsvcs] LUIS - add text to simple entity description

- lib/services/cognitiveServicesFace/lib/models/detectedFace.js
- lib/services/cognitiveServicesFace/lib/models/faceAttributes.js
- lib/services/cognitiveServicesFace/lib/models/index.d.ts
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5188
> [AutoPR cognitiveservices/data-plane/Face] [Cogs Face] Remove Face API reference of Gender::genderless to avoid confusion.

- .azure-pipelines/client.yml
- Fixes #4643
CC: @Azure/azure-sdk-eng
> Update pipeline job names and dependencies

- lib/services/containerservicesManagement/lib/models/agentPool.js
- lib/services/containerservicesManagement/lib/models/index.d.ts
- lib/services/containerservicesManagement/lib/models/managedCluster.js
- lib/services/containerservicesManagement/lib/models/managedClusterAgentPoolProfileProperties.js
- lib/services/containerservicesManagement/lib/operations/index.d.ts
- lib/services/containerservicesManagement/lib/operations/managedClusters.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5310
> [AutoPR containerservice/resource-manager] mark the new features as PREVIEW in description 

- lib/services/batch/LICENSE.txt
- lib/services/batch/lib/models/cloudJob.js
- lib/services/batch/lib/models/cloudPool.js
- lib/services/batch/lib/models/computeNode.js
- lib/services/batch/lib/models/index.d.ts
- lib/services/batch/lib/models/multiInstanceSettings.js
- lib/services/batch/lib/models/resourceFile.js
- lib/services/batch/lib/models/virtualMachineConfiguration.js
- lib/services/batch/lib/operations/account.js
- lib/services/batch/lib/operations/application.js
- lib/services/batch/lib/operations/certificateOperations.js
- lib/services/batch/lib/operations/computeNodeOperations.js
- lib/services/batch/lib/operations/file.js
- lib/services/batch/lib/operations/index.d.ts
- lib/services/batch/lib/operations/job.js
- lib/services/batch/lib/operations/jobSchedule.js
- lib/services/batch/lib/operations/pool.js
- lib/services/batch/lib/operations/task.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5305
> [AutoPR batch/data-plane] Update some descriptions.

- lib/services/eventHubManagement/lib/operations/namespaces.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5360
> [AutoPR eventhub/resource-manager] EventHub : corrected typo 

- lib/services/monitorManagement/README.md
- lib/services/monitorManagement/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5373
> [AutoPR monitor/resource-manager] Add insights 2019-03-01 package to Go SDK

- lib/services/monitorManagement/lib/models/armRoleReceiver.js
- lib/services/monitorManagement/lib/models/automationRunbookReceiver.js
- lib/services/monitorManagement/lib/models/azureFunctionReceiver.js
- lib/services/monitorManagement/lib/models/emailReceiver.js
- lib/services/monitorManagement/lib/models/index.d.ts
- lib/services/monitorManagement/lib/models/logicAppReceiver.js
- lib/services/monitorManagement/lib/models/webhookReceiver.js
- lib/services/monitorManagement/lib/operations/actionGroups.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5378
> [AutoPR monitor/resource-manager] fix package tag for new API version

- lib/services/policyinsightsManagement/README.md
- lib/services/policyinsightsManagement/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5389
> [AutoPR policyinsights/resource-manager] Fix PolicyInsights code generation issue

- lib/services/marketplaceorderingManagement/README.md
- lib/services/marketplaceorderingManagement/lib/operations/marketplaceAgreements.js
- lib/services/marketplaceorderingManagement/package.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5412
> [AutoPR marketplaceordering/resource-manager] [Hub Generated] Review request for Microsoft.MarketplaceOrdering to add version 2015-06-01

- .azure-pipelines/client.yml
Plans aren't solid enough to justify blocking anyone in this repo.
> Remove Readme Verification

- lib/services/storageManagement2/lib/operations/index.d.ts
- lib/services/storageManagement2/lib/operations/storageAccounts.js
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5453
> [AutoPR storage/resource-manager] Added feature revoke user delegation key

- .azure-pipelines/client.yml
> Added build step to verify agent OS

- lib/services/keyVault/README.md
- lib/services/keyVault/lib/keyVaultClient.d.ts
- lib/services/keyVault/package.json
fixes https://github.com/Azure/azure-sdk-for-node/issues/4820
> update keyvault readme and re-export KeyVaultCredentials from ms-rest-azure

- runtime/ms-rest/Changelog.md
- runtime/ms-rest/lib/serialization.js
- runtime/ms-rest/lib/webResource.js
- runtime/ms-rest/package.json
Body is not a required property and can be undefined.
> Remove the body initialization for null.

- lib/common/package.json
- lib/services/legacyStorage/lib/blob/blobservice.js
- package.json
- test/services/blob/blobservice-tests.js
- test/services/queue/queueservice-tests.js
- test/services/table/tableservice-tests.js
> Update out-dated dependencies

- lib/common/lib/util/constants.js
- lib/services/serviceBus/lib/apnsservice.js
Co-authored-by: Ajith Kumar <ajithpoison@gmail.com>
> expiry fix and add priority

- runtime/ms-rest/.vscode/launch.json
The file has invalid syntax and was breaking flowjs.
> Invalid syntax

- runtime/ms-rest-azure/Changelog.md
This PR updates the changelog for `ms-rest-azure` to include notes for the past 2 releases
> Changelog update for ms-rest-azure 2.6.0 & 3.0.0

- .azure-pipelines/client.yml
- lib/services/resourceManagement/lib/feature/models/index.d.ts
- lib/services/resourceManagement/lib/link/models/index.d.ts
- lib/services/resourceManagement/lib/lock/models/index.d.ts
- lib/services/resourceManagement/lib/management/models/index.d.ts
- lib/services/resourceManagement/lib/models/index.d.ts
- lib/services/resourceManagement/lib/policy/models/index.d.ts
- lib/services/resourceManagement/lib/resource/models/index.d.ts
- lib/services/resourceManagement/lib/subscription/models/index.d.ts
- lib/services/resourceManagement/package.json
- runtime/ms-rest-azure/index.d.ts
> Fix invalid reference

- Documentation/Authentication.md
- lib/services/graphManagement/README.md
Creating a PR with same changes as #5183 to test if CI works better here
> Update docs to use https://graph.windows.net as tokenAudience for graph

- lib/services/datalake.Store/README.md
- lib/services/datalake.Store/package.json
> fix the doc for datalake store

- runtime/ms-rest-azure/Changelog.md
- runtime/ms-rest-azure/package.json
- runtime/ms-rest-azure/test/package.json
remove moment dependency in ms-rest-azure for issue #5157
> remove moment in ms-rest-azure

- .config/CredScanSuppressions.json
- README.md
- lib/common/package.json
- runtime/ms-rest/package.json
This PR is trying to fix 
1. validator vulnerability issues in azure-common #5222 #5215 #5214
2. json-schema vulnerability issues in ms-rest #5221 #5218
> to resolve security related issues

- package.json
- runtime/ms-rest-azure/package.json
> try fix cg issue for ms-rest-azure 3.x.x
